### ISSUE TITLE
Error Installing Kubernetes on AWS using Conjure-up

### ISSUE THREAD

**Issue by Desmondwong** [conjure-up/conjure-up#1311] opened 2018-01-19 12:36 UTC
## Report

Thank you for trying **conjure-up**! Before reporting a bug please make sure you've gone through this checklist:

- [no ] Is this problem already documented at https://docs.ubuntu.com/conjure-up/en/troubleshoot#common-spell-problems
- [yes ] Is conjure-up running inside a virtual machine?
- [no ] Is this problem reproducible with `sudo snap refresh conjure-up --edge`?

## Please provide the output of the following commands
Oops, there was a problem with your install:        
                                                                                                   
  ─────────────────────────────────────────────────────────────────────────────────────────────────
                                                                                                   
       Reason: 

[Errno 110] Connect call failed ('52.213.20.147', 17070)                          
                                                                                            
           Review log messages at /home/ubuntu/.cache/conjure-up/conjure-up.log If          
          appropriate, please submit a bug here:                                            
          https://github.com/conjure-up/conjure-up/issues/new

 Oops, there was a problem with your install:        
                                                                                                   
  ─────────────────────────────────────────────────────────────────────────────────────────────────
                                                                                                   
       Reason:                                                                                
          [Errno 110] Connect call failed ('54.86.114.126', 17070)                          
                                                                                            
           Review log messages at /home/ubuntu/.cache/conjure-up/conjure-up.log If          
          appropriate, please submit a bug here:                                            
          https://github.com/conjure-up/conjure-up/issues/new                               

```
which juju
juju version
2.3.1-xenial-amd64

which conjure-up
conjure-up --version
conjure-up 2.5.2


which lxc
/snap/bin/lxc config show
/snap/bin/lxc version

cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.3 LTS"

Please attach tarball of **~/.cache/conjure-up**:

```
tar cvzf conjure-up.tar.gz ~/.cache/conjure-up
```

## Sosreport

Please attach a sosreport:

```
sudo apt install sosreport
sosreport
```

The resulting output file can be attached to this issue.


## What Spell was Selected?

## What provider (aws, maas, localhost, etc)?

### MAAS Users
Which version of MAAS?

## Commands ran

Please outline what commands were run to install and execute conjure-up:

## Additional Information

**Comment by battlemidget** [comment] 2018-01-19 20:40
Can you please provide the output of `~/.cache/conjure-up/conjure-up.log` as stated in the issue template and error message?

**Comment by Desmondwong** [comment] 2018-01-28 03:50
sudo: unable to resolve host ip-192-168-1-38
2018-01-28 03:36:27,153 [DEBUG] conjure-up/_unspecified_spell - juju.py:39 - bin_path candidate found
2018-01-28 03:36:27,153 [DEBUG] conjure-up/_unspecified_spell - juju.py:39 - wait_path candidate found
2018-01-28 03:36:29,915 [DEBUG] conjure-up/_unspecified_spell - app.py:254 - Juju version: 2.3.1-xenial-amd64, conjure-up version: 2.5.2
2018-01-28 03:36:29,943 [DEBUG] conjure-up/_unspecified_spell - telemetry.py:17 - Showing screen: Application Start
2018-01-28 03:36:29,945 [DEBUG] conjure-up/_unspecified_spell - telemetry.py:31 - OS: Linux-4.4.0-1047-aws-x86_64-with-debian-stretch-sid 
2018-01-28 03:36:29,948 [INFO] conjure-up/_unspecified_spell - events.py:172 - Watching for shutdown
2018-01-28 03:36:29,990 [DEBUG] conjure-up/_unspecified_spell - events.py:53 - Awaiting Shutdown at conjureup/events.py:175
2018-01-28 03:36:29,998 [DEBUG] conjure-up/_unspecified_spell - telemetry.py:17 - Showing screen: Spell Picker
2018-01-28 03:36:48,762 [DEBUG] conjure-up/_unspecified_spell - telemetry.py:31 - Spell Choice: canonical-kubernetes 
2018-01-28 03:36:48,763 [DEBUG] conjure-up/canonical-kubernetes - download.py:60 - Path is local filesystem, copying /snap/conjure-up/924/spells/canonical-kubernetes to /home/desmond/.cache/conjure-up/canonical-kubernetes
2018-01-28 03:36:48,953 [DEBUG] conjure-up/canonical-kubernetes - step.py:27 - steps: [<StepModel Canonical Distribution of Kubernetes 00_process-providertype v: False c: []>, <StepModel Canonical Distribution of Kubernetes 01_select-network v: True c: []>, <StepModel Canonical Distribution of Kubernetes 02_get-kubectl v: True c: []>, <StepModel Canonical Distribution of Kubernetes 03_cluster-info v: True c: []>, <StepModel Canonical Distribution of Kubernetes 04_enable-cni v: False c: []>]
2018-01-28 03:36:49,190 [DEBUG] conjure-up/canonical-kubernetes - utils.py:513 - Pulling bundle for canonical-kubernetes from channel: stable
2018-01-28 03:36:52,120 [DEBUG] conjure-up/canonical-kubernetes - telemetry.py:17 - Showing screen: Add-on Selection
2018-01-28 03:36:57,356 [DEBUG] conjure-up/canonical-kubernetes - telemetry.py:17 - Showing screen: Cloud Select
2018-01-28 03:36:58,027 [DEBUG] conjure-up/canonical-kubernetes - gui.py:79 - Starting watcher for verifying LXD server is available.
2018-01-28 03:36:58,027 [DEBUG] conjure-up/canonical-kubernetes - provider.py:369 - LXD environment set: binary /usr/bin/lxc lxd_dir /var/lib/lxd
2018-01-28 03:36:58,037 [DEBUG] conjure-up/canonical-kubernetes - provider.py:369 - LXD environment set: binary /usr/bin/lxc lxd_dir /var/lib/lxd
2018-01-28 03:36:58,534 [DEBUG] conjure-up/canonical-kubernetes - provider.py:384 - LXD query cmd: /usr/bin/lxc query --wait -X GET /1.0
2018-01-28 03:36:58,551 [ERROR] conjure-up/canonical-kubernetes - provider.py:391 - Unable to parse JSON output from LXD, does `/usr/bin/lxc query --wait -X GET /1.0` return info about the LXD server?
2018-01-28 03:36:59,939 [DEBUG] conjure-up/canonical-kubernetes - telemetry.py:31 - Cloud selection: aws 
2018-01-28 03:37:00,054 [DEBUG] conjure-up/canonical-kubernetes - telemetry.py:17 - Showing screen: New Credential Creation
2018-01-28 03:37:20,682 [DEBUG] conjure-up/canonical-kubernetes - telemetry.py:17 - Showing screen: Choose a Region
2018-01-28 03:37:31,309 [DEBUG] conjure-up/canonical-kubernetes - telemetry.py:17 - Showing screen: Controller Picker
2018-01-28 03:37:32,817 [DEBUG] conjure-up/canonical-kubernetes - telemetry.py:17 - Showing screen: JaaS Login Wait
2018-01-28 03:37:32,820 [INFO] conjure-up/canonical-kubernetes - gui.py:24 - Attempting to register JAAS with saved token
2018-01-28 03:37:32,820 [INFO] conjure-up/canonical-kubernetes - juju.py:250 - Registering controller jaas
2018-01-28 03:37:37,646 [WARNING] conjure-up/canonical-kubernetes - juju.py:277 - Registration failed: ERROR cannot log into "jimm.jujucharms.com": cannot get token: Invalid request data (email: [Enter a valid email address.])

2018-01-28 03:37:37,647 [DEBUG] conjure-up/canonical-kubernetes - telemetry.py:17 - Showing screen: Login to JaaS
2018-01-28 03:37:59,105 [DEBUG] conjure-up/canonical-kubernetes - telemetry.py:17 - Showing screen: JaaS Login Wait
2018-01-28 03:37:59,106 [INFO] conjure-up/canonical-kubernetes - juju.py:250 - Registering controller jaas
2018-01-28 03:38:06,535 [INFO] conjure-up/canonical-kubernetes - juju.py:283 - Registration complete
2018-01-28 03:38:06,535 [INFO] conjure-up/canonical-kubernetes - gui.py:57 - JAAS is registered
2018-01-28 03:38:06,541 [DEBUG] conjure-up/canonical-kubernetes - telemetry.py:17 - Showing screen: Configure Spell
2018-01-28 03:38:09,323 [DEBUG] conjure-up/canonical-kubernetes - step.py:101 - Contents: (<Padding selectable flow widget <AttrMap selectable flow widget <PlainButton selectable flow widget 'Next'> attr_map={None: 'button_primary'} focus_map={None: 'button_primary focus'}> align='right' width=('relative', 20)>, ('weight', 1))
2018-01-28 03:38:09,323 [DEBUG] conjure-up/canonical-kubernetes - step.py:101 - Contents: (<Text flow widget ''>, ('weight', 1))
2018-01-28 03:38:09,324 [INFO] conjure-up/canonical-kubernetes - step.py:206 - Running Canonical Distribution of Kubernetes step: 01_select-network after-input.
2018-01-28 03:38:09,476 [DEBUG] conjure-up/canonical-kubernetes - step.py:244 - Storing environment
2018-01-28 03:38:09,483 [DEBUG] conjure-up/canonical-kubernetes - step.py:250 - Executing script: /home/desmond/.cache/conjure-up/canonical-kubernetes/steps/01_select-network/after-input
2018-01-28 03:38:15,283 [DEBUG] conjure-up/canonical-kubernetes - step.py:101 - Contents: (<Padding selectable flow widget <AttrMap selectable flow widget <PlainButton selectable flow widget 'Next'> attr_map={None: 'button_primary'} focus_map={None: 'button_primary focus'}> align='right' width=('relative', 20)>, ('weight', 1))
2018-01-28 03:38:15,328 [DEBUG] conjure-up/canonical-kubernetes - step.py:101 - Contents: (<Text flow widget ''>, ('weight', 1))
2018-01-28 03:38:15,436 [DEBUG] conjure-up/canonical-kubernetes - telemetry.py:17 - Showing screen: Configure Applications
2018-01-28 03:38:18,031 [DEBUG] conjure-up/canonical-kubernetes - telemetry.py:17 - Showing screen: Bootstrap
2018-01-28 03:38:20,814 [INFO] conjure-up/canonical-kubernetes - common.py:66 - Creating Juju model.
2018-01-28 03:38:31,353 [DEBUG] conjure-up/canonical-kubernetes - events.py:53 - Setting ModelAvailable at conjureup/juju.py:882 in task run at conjureup/controllers/bootstrap/common.py:19
2018-01-28 03:38:31,353 [INFO] conjure-up/canonical-kubernetes - juju.py:166 - Connecting to model jaas:conjure-canonical-kubern-62e...
2018-01-28 03:38:32,539 [INFO] conjure-up/canonical-kubernetes - websocket: connection.py:163 - Driver connected to juju wss://jimm.jujucharms.com:443/model/e61cc015-6e15-4b33-835c-61e7c05b71dc/api
2018-01-28 03:38:32,833 [INFO] conjure-up/canonical-kubernetes - websocket: connection.py:390 - Controller requested redirect
2018-01-28 03:38:34,231 [INFO] conjure-up/canonical-kubernetes - websocket: connection.py:163 - Driver connected to juju wss://1.us-east-1.aws.jaas.jujucharms.com:443/model/e61cc015-6e15-4b33-835c-61e7c05b71dc/api
2018-01-28 03:38:34,438 [INFO] conjure-up/canonical-kubernetes - websocket: connection.py:382 - Macaroon discharge required, disconnecting
2018-01-28 03:40:41,883 [DEBUG] conjure-up/canonical-kubernetes - events.py:53 - Setting Error at conjureup/events.py:148
2018-01-28 03:40:41,883 [ERROR] conjure-up/canonical-kubernetes - events.py:160 - Unhandled exception in <Task finished coro=<BaseBootstrapController.run() done, defined at /snap/conjure-up/924/lib/python3.6/site-packages/conjureup/controllers/bootstrap/common.py:15> exception=TimeoutError(110, "Connect call failed ('54.86.114.126', 17070)")>
Traceback (most recent call last):
  File "/snap/conjure-up/924/lib/python3.6/site-packages/conjureup/controllers/bootstrap/common.py", line 19, in run
    await self.do_add_model()
  File "/snap/conjure-up/924/lib/python3.6/site-packages/conjureup/controllers/bootstrap/common.py", line 32, in do_add_model
    app.provider.credential)
  File "/snap/conjure-up/924/lib/python3.6/site-packages/conjureup/juju.py", line 883, in add_model
    await login()
  File "/snap/conjure-up/924/lib/python3.6/site-packages/conjureup/juju.py", line 167, in login
    await app.juju.client.connect_model(model_name)
  File "/snap/conjure-up/924/lib/python3.6/site-packages/juju/model.py", line 457, in connect_model
    model_name, self.loop, self.max_frame_size)
  File "/snap/conjure-up/924/lib/python3.6/site-packages/juju/client/connection.py", line 529, in connect_model
    max_frame_size)
  File "/snap/conjure-up/924/lib/python3.6/site-packages/juju/client/connection.py", line 445, in connect
    await client._connect()
  File "/snap/conjure-up/924/lib/python3.6/site-packages/juju/client/connection.py", line 418, in _connect
    _endpoint, _cacert)
  File "/snap/conjure-up/924/lib/python3.6/site-packages/juju/client/connection.py", line 378, in _try_endpoint
    await self.open()
  File "/snap/conjure-up/924/lib/python3.6/site-packages/juju/client/connection.py", line 160, in open
    self.ws = await websockets.connect(url, **kw)
  File "/snap/conjure-up/924/lib/python3.6/site-packages/websockets/client.py", line 393, in __await__
    transport, protocol = yield from self._creating_connection
  File "/snap/conjure-up/924/usr/lib/python3.6/asyncio/base_events.py", line 777, in create_connection
    raise exceptions[0]
  File "/snap/conjure-up/924/usr/lib/python3.6/asyncio/base_events.py", line 764, in create_connection
    yield from self.sock_connect(sock, address)
  File "/snap/conjure-up/924/usr/lib/python3.6/asyncio/selector_events.py", line 451, in sock_connect
    return (yield from fut)
  File "/snap/conjure-up/924/usr/lib/python3.6/asyncio/selector_events.py", line 481, in _sock_connect_cb
    raise OSError(err, 'Connect call failed %s' % (address,))
TimeoutError: [Errno 110] Connect call failed ('54.86.114.126', 17070)
2018-01-28 03:40:41,893 [DEBUG] conjure-up/canonical-kubernetes - __init__.py:24 - Showing dialog for exception: [Errno 110] Connect call failed ('54.86.114.126', 17070)

**Comment by Desmondwong** [comment] 2018-01-28 03:52
Here is the output:

sudo: unable to resolve host ip-192-168-1-38
2018-01-28 03:36:27,153 [DEBUG] conjure-up/_unspecified_spell - juju.py:39
- bin_path candidate found
2018-01-28 03:36:27,153 [DEBUG] conjure-up/_unspecified_spell - juju.py:39
- wait_path candidate found
2018-01-28 03:36:29,915 [DEBUG] conjure-up/_unspecified_spell - app.py:254
- Juju version: 2.3.1-xenial-amd64, conjure-up version: 2.5.2
2018-01-28 03:36:29,943 [DEBUG] conjure-up/_unspecified_spell -
telemetry.py:17 - Showing screen: Application Start
2018-01-28 03:36:29,945 [DEBUG] conjure-up/_unspecified_spell -
telemetry.py:31 - OS: Linux-4.4.0-1047-aws-x86_64-with-debian-stretch-sid
2018-01-28 03:36:29,948 [INFO] conjure-up/_unspecified_spell -
events.py:172 - Watching for shutdown
2018-01-28 03:36:29,990 [DEBUG] conjure-up/_unspecified_spell -
events.py:53 - Awaiting Shutdown at conjureup/events.py:175
2018-01-28 03:36:29,998 [DEBUG] conjure-up/_unspecified_spell -
telemetry.py:17 - Showing screen: Spell Picker
2018-01-28 03:36:48,762 [DEBUG] conjure-up/_unspecified_spell -
telemetry.py:31 - Spell Choice: canonical-kubernetes
2018-01-28 03:36:48,763 [DEBUG] conjure-up/canonical-kubernetes -
download.py:60 - Path is local filesystem, copying
/snap/conjure-up/924/spells/canonical-kubernetes to
/home/desmond/.cache/conjure-up/canonical-kubernetes
2018-01-28 03:36:48,953 [DEBUG] conjure-up/canonical-kubernetes -
step.py:27 - steps: [<StepModel Canonical Distribution of Kubernetes
00_process-providertype v: False c: []>, <StepModel Canonical Distribution
of Kubernetes 01_select-network v: True c: []>, <StepModel Canonical
Distribution of Kubernetes 02_get-kubectl v: True c: []>, <StepModel
Canonical Distribution of Kubernetes 03_cluster-info v: True c: []>,
<StepModel Canonical Distribution of Kubernetes 04_enable-cni v: False c:
[]>]
2018-01-28 03:36:49,190 [DEBUG] conjure-up/canonical-kubernetes -
utils.py:513 - Pulling bundle for canonical-kubernetes from channel: stable
2018-01-28 03:36:52,120 [DEBUG] conjure-up/canonical-kubernetes -
telemetry.py:17 - Showing screen: Add-on Selection
2018-01-28 03:36:57,356 [DEBUG] conjure-up/canonical-kubernetes -
telemetry.py:17 - Showing screen: Cloud Select
2018-01-28 03:36:58,027 [DEBUG] conjure-up/canonical-kubernetes - gui.py:79
- Starting watcher for verifying LXD server is available.
2018-01-28 03:36:58,027 [DEBUG] conjure-up/canonical-kubernetes -
provider.py:369 - LXD environment set: binary /usr/bin/lxc lxd_dir
/var/lib/lxd
2018-01-28 03:36:58,037 [DEBUG] conjure-up/canonical-kubernetes -
provider.py:369 - LXD environment set: binary /usr/bin/lxc lxd_dir
/var/lib/lxd
2018-01-28 03:36:58,534 [DEBUG] conjure-up/canonical-kubernetes -
provider.py:384 - LXD query cmd: /usr/bin/lxc query --wait -X GET /1.0
2018-01-28 03:36:58,551 [ERROR] conjure-up/canonical-kubernetes -
provider.py:391 - Unable to parse JSON output from LXD, does `/usr/bin/lxc
query --wait -X GET /1.0` return info about the LXD server?
2018-01-28 03:36:59,939 [DEBUG] conjure-up/canonical-kubernetes -
telemetry.py:31 - Cloud selection: aws
2018-01-28 03:37:00,054 [DEBUG] conjure-up/canonical-kubernetes -
telemetry.py:17 - Showing screen: New Credential Creation
2018-01-28 03:37:20,682 [DEBUG] conjure-up/canonical-kubernetes -
telemetry.py:17 - Showing screen: Choose a Region
2018-01-28 03:37:31,309 [DEBUG] conjure-up/canonical-kubernetes -
telemetry.py:17 - Showing screen: Controller Picker
2018-01-28 03:37:32,817 [DEBUG] conjure-up/canonical-kubernetes -
telemetry.py:17 - Showing screen: JaaS Login Wait
2018-01-28 03:37:32,820 [INFO] conjure-up/canonical-kubernetes - gui.py:24
- Attempting to register JAAS with saved token
2018-01-28 03:37:32,820 [INFO] conjure-up/canonical-kubernetes -
juju.py:250 - Registering controller jaas
2018-01-28 03:37:37,646 [WARNING] conjure-up/canonical-kubernetes -
juju.py:277 - Registration failed: ERROR cannot log into "
jimm.jujucharms.com": cannot get token: Invalid request data (email: [Enter
a valid email address.])

2018-01-28 03:37:37,647 [DEBUG] conjure-up/canonical-kubernetes -
telemetry.py:17 - Showing screen: Login to JaaS
2018-01-28 03:37:59,105 [DEBUG] conjure-up/canonical-kubernetes -
telemetry.py:17 - Showing screen: JaaS Login Wait
2018-01-28 03:37:59,106 [INFO] conjure-up/canonical-kubernetes -
juju.py:250 - Registering controller jaas
2018-01-28 03:38:06,535 [INFO] conjure-up/canonical-kubernetes -
juju.py:283 - Registration complete
2018-01-28 03:38:06,535 [INFO] conjure-up/canonical-kubernetes - gui.py:57
- JAAS is registered
2018-01-28 03:38:06,541 [DEBUG] conjure-up/canonical-kubernetes -
telemetry.py:17 - Showing screen: Configure Spell
2018-01-28 03:38:09,323 [DEBUG] conjure-up/canonical-kubernetes -
step.py:101 - Contents: (<Padding selectable flow widget <AttrMap
selectable flow widget <PlainButton selectable flow widget 'Next'>
attr_map={None: 'button_primary'} focus_map={None: 'button_primary focus'}>
align='right' width=('relative', 20)>, ('weight', 1))
2018-01-28 03:38:09,323 [DEBUG] conjure-up/canonical-kubernetes -
step.py:101 - Contents: (<Text flow widget ''>, ('weight', 1))
2018-01-28 03:38:09,324 [INFO] conjure-up/canonical-kubernetes -
step.py:206 - Running Canonical Distribution of Kubernetes step:
01_select-network after-input.
2018-01-28 03:38:09,476 [DEBUG] conjure-up/canonical-kubernetes -
step.py:244 - Storing environment
2018-01-28 03:38:09,483 [DEBUG] conjure-up/canonical-kubernetes -
step.py:250 - Executing script:
/home/desmond/.cache/conjure-up/canonical-kubernetes/steps/01_select-network/after-input
2018-01-28 03:38:15,283 [DEBUG] conjure-up/canonical-kubernetes -
step.py:101 - Contents: (<Padding selectable flow widget <AttrMap
selectable flow widget <PlainButton selectable flow widget 'Next'>
attr_map={None: 'button_primary'} focus_map={None: 'button_primary focus'}>
align='right' width=('relative', 20)>, ('weight', 1))
2018-01-28 03:38:15,328 [DEBUG] conjure-up/canonical-kubernetes -
step.py:101 - Contents: (<Text flow widget ''>, ('weight', 1))
2018-01-28 03:38:15,436 [DEBUG] conjure-up/canonical-kubernetes -
telemetry.py:17 - Showing screen: Configure Applications
2018-01-28 03:38:18,031 [DEBUG] conjure-up/canonical-kubernetes -
telemetry.py:17 - Showing screen: Bootstrap
2018-01-28 03:38:20,814 [INFO] conjure-up/canonical-kubernetes -
common.py:66 - Creating Juju model.
2018-01-28 03:38:31,353 [DEBUG] conjure-up/canonical-kubernetes -
events.py:53 - Setting ModelAvailable at conjureup/juju.py:882 in task run
at conjureup/controllers/bootstrap/common.py:19
2018-01-28 03:38:31,353 [INFO] conjure-up/canonical-kubernetes -
juju.py:166 - Connecting to model jaas:conjure-canonical-kubern-62e...
2018-01-28 03:38:32,539 [INFO] conjure-up/canonical-kubernetes - websocket:
connection.py:163 - Driver connected to juju wss://
jimm.jujucharms.com:443/model/e61cc015-6e15-4b33-835c-61e7c05b71dc/api
2018-01-28 03:38:32,833 [INFO] conjure-up/canonical-kubernetes - websocket:
connection.py:390 - Controller requested redirect
2018-01-28 03:38:34,231 [INFO] conjure-up/canonical-kubernetes - websocket:
connection.py:163 - Driver connected to juju wss://
1.us-east-1.aws.jaas.jujucharms.com:443/model/e61cc015-6e15-4b33-835c-61e7c05b71dc/api
2018-01-28 03:38:34,438 [INFO] conjure-up/canonical-kubernetes - websocket:
connection.py:382 - Macaroon discharge required, disconnecting
2018-01-28 03:40:41,883 [DEBUG] conjure-up/canonical-kubernetes -
events.py:53 - Setting Error at conjureup/events.py:148
2018-01-28 03:40:41,883 [ERROR] conjure-up/canonical-kubernetes -
events.py:160 - Unhandled exception in <Task finished
coro=<BaseBootstrapController.run() done, defined at
/snap/conjure-up/924/lib/python3.6/site-packages/conjureup/controllers/bootstrap/common.py:15>
exception=TimeoutError(110, "Connect call failed ('54.86.114.126', 17070)")>
Traceback (most recent call last):
  File
"/snap/conjure-up/924/lib/python3.6/site-packages/conjureup/controllers/bootstrap/common.py",
line 19, in run
    await self.do_add_model()
  File
"/snap/conjure-up/924/lib/python3.6/site-packages/conjureup/controllers/bootstrap/common.py",
line 32, in do_add_model
    app.provider.credential)
  File
"/snap/conjure-up/924/lib/python3.6/site-packages/conjureup/juju.py", line
883, in add_model
    await login()
  File
"/snap/conjure-up/924/lib/python3.6/site-packages/conjureup/juju.py", line
167, in login
    await app.juju.client.connect_model(model_name)
  File "/snap/conjure-up/924/lib/python3.6/site-packages/juju/model.py",
line 457, in connect_model
    model_name, self.loop, self.max_frame_size)
  File
"/snap/conjure-up/924/lib/python3.6/site-packages/juju/client/connection.py",
line 529, in connect_model
    max_frame_size)
  File
"/snap/conjure-up/924/lib/python3.6/site-packages/juju/client/connection.py",
line 445, in connect
    await client._connect()
  File
"/snap/conjure-up/924/lib/python3.6/site-packages/juju/client/connection.py",
line 418, in _connect
    _endpoint, _cacert)
  File
"/snap/conjure-up/924/lib/python3.6/site-packages/juju/client/connection.py",
line 378, in _try_endpoint
    await self.open()
  File
"/snap/conjure-up/924/lib/python3.6/site-packages/juju/client/connection.py",
line 160, in open
    self.ws = await websockets.connect(url, **kw)
  File
"/snap/conjure-up/924/lib/python3.6/site-packages/websockets/client.py",
line 393, in __await__
    transport, protocol = yield from self._creating_connection
  File "/snap/conjure-up/924/usr/lib/python3.6/asyncio/base_events.py",
line 777, in create_connection
    raise exceptions[0]
  File "/snap/conjure-up/924/usr/lib/python3.6/asyncio/base_events.py",
line 764, in create_connection
    yield from self.sock_connect(sock, address)
  File "/snap/conjure-up/924/usr/lib/python3.6/asyncio/selector_events.py",
line 451, in sock_connect
    return (yield from fut)
  File "/snap/conjure-up/924/usr/lib/python3.6/asyncio/selector_events.py",
line 481, in _sock_connect_cb
    raise OSError(err, 'Connect call failed %s' % (address,))
TimeoutError: [Errno 110] Connect call failed ('54.86.114.126', 17070)
2018-01-28 03:40:41,893 [DEBUG] conjure-up/canonical-kubernetes -
__init__.py:24 - Showing dialog for exception: [Errno 110] Connect call
failed ('54.86.114.126', 17070)

**Comment by battlemidget** [comment] 2018-01-28 13:35
@johnsca interesting. looks like another jaas connection

**Comment by Desmondwong** [comment] 2018-01-28 20:28
Why another?    Previous configuration was great and now it does not work
anymore.  Please help.

**Comment by battlemidget** [comment] 2018-01-29 00:32
Because we've seen other connection failures with jaas. You could try with a self hosted controller instead

**Comment by Desmondwong** [comment] 2018-01-29 01:05
* I have tried "self hosted controller "  many times and it still failed.*

**Comment by Desmondwong** [comment] 2018-01-29 01:09
Conjure-up is behaving erratic and I could not use it in production.  I
want a stable and predictable environment.  Can you suggest a solution?

**Comment by johnsca** [comment] 2018-02-12 18:04
After doing some digging, it looks like `juju add-model` isn't creating an authenticated macaroon like we thought, meaning success would depend on whether you had used the CLI in the selected region recently.  Full macaroon support in the library is in progress, but in the meantime we should be able to use a `juju status` call to force the CLI to create the macaroon for us.

**Comment by Desmondwong** [comment] 2018-02-12 22:18
If human intervention is required, conjure-up should spell out clearly with
a message.  At this stage, there are many things we do not know behind juju
??????

I don't like hidden things that I can not see.

**Comment by battlemidget** [comment] 2018-02-12 22:34
> If human intervention is required, conjure-up should spell out clearly with
> a message.  At this stage, there are many things we do not know behind juju
> ??????

We do when that is required. In this case it shouldn't be required. If you want to know what is going on wrt to Juju, you can find all the logs in `~/.cache/conjure-up/`.

**Comment by johnsca** [comment] 2018-02-12 22:37
Perhaps my comment was unclear.  `conjure-up` is a front-end for `juju`, providing an interactive workflow for the `juju` commands that can also be accomplished directly via the CLI if you are familiar with `juju`.  One of the commands that `conjure-up` uses to attempt to ensure the model it just asked `juju` to create is available is `juju status`.  That call should leave us with a discharged (authenticated) macaroon which `conjure-up` then uses to log in to the model.  There should be no manual intervention required, though in debugging I did notice that using `juju status` manually via the CLI did result in a discharged macaroon even though the call that is done by `conjure-up` somehow doesn't.  This may be a race condition, though I'm pretty consistently able to reproduce it on a fresh machine (once `juju status` is used manually from the command line, `conjure-up` works fine from then on, which is why we had trouble figuring out how to reproduce this; but that manual step definitely should not be required).

**Comment by johnsca** [comment] 2018-02-12 22:38
@battlemidget I believe we talked about creating some docs detailing the equivalent `juju` commands for what `conjure-up` does interactively.  That would be good to have so that it's more clear what is happening.

**Comment by Desmondwong** [comment] 2018-02-13 00:41
Thanks Cory,

I have been reading lots of documentation on Conjure-up and juju and I
still could not find those hidden behind the scene.  I got this impression
that some unemployed aliens were working behind Conjure-up.  A good
documentation is important.  Can you tell me where to find the
configuration on volume and size of those automated created workers when
Conjure-up Kubernetes is used?

**Comment by johnsca** [comment] 2018-02-13 17:30
`conjure-up` is driven by the spells in the [spells repo](https://github.com/conjure-up/spells) and the canonical-kubernetes spell just deploys the [canonical-kubernetes bundle](https://jujucharms.com/canonical-kubernetes/) (see the [`metadata.yaml` in the spell](https://github.com/conjure-up/spells/blob/master/canonical-kubernetes/metadata.yaml)).  The bundle [defines](https://api.jujucharms.com/charmstore/v5/canonical-kubernetes/archive/bundle.yaml) default (minimum) constraints of `cores=4 mem=4G` for the worker units, though those can be modified in `conjure-up` via the UI.

You can use `juju deploy canonical-kubernetes` to deploy the bundle directly, but the spells do also contain some additional [steps](https://github.com/conjure-up/spells/tree/master/canonical-kubernetes/steps) to do things like configure kubectl with the cluster info, or other specialized setup for deploying on specific providers that you might have to do manually otherwise.  The spells also provide support for [adding on](https://github.com/conjure-up/spells/tree/master/canonical-kubernetes/addons) additional components, like Graylog integration.  Essentially, the bundle is the core deployment, the spells codify additional options and configuration that can be done, and `conjure-up` provides a UI for selecting all of the various options and passing them in to `juju`.

**Comment by Desmondwong** [comment] 2018-02-14 11:22
Cory,

I created Kubernetes using Conjure-up on a desktop server, it automatically
used up 100 gigabytes of harddisk space.  This is what I uncovered on my
harddisk.

/dev/loop5          12288     12288          0 100% /snap/kubectl/303
/dev/loop3            128       128          0 100% /snap/kubefed/297
/dev/loop4          46720     46720          0 100% /snap/lxd/5729
/dev/loop1          47360     47360          0 100% /snap/lxd/5671
/dev/loop2          47232     47232          0 100% /snap/lxd/5612
/dev/loop6          89088     89088          0 100% /snap/conjure-up/924
/dev/loop0          83328     83328          0 100% /snap/core/3887

When I created Kubernetes using Conjure-up on AWS, it does not tell me how
much harddisk are used.  Do you know how to find out the actual allocation
apart from using df to find out the diskspace?  Can I change the allocation?

**Comment by battlemidget** [comment] 2018-02-16 18:44
@Desmondwong can you try now with `sudo snap refresh conjure-up --edge`.

**Comment by Desmondwong** [comment] 2018-02-17 05:23
Adam,

I got this message when I ran your command on my local server (with
Kubernetes).

desmond is fantastic @ $ sudo snap refresh conjure-up --edge
error: cannot refresh "conjure-up": cannot refresh snap-declaration for
"conjure-up": Get

https://api.snapcraft.io/api/v1/snaps/assertions/snap-declaration/16/ijQR4HjYlTAmIjELJm5XCpNAqbDZWJ3h?max-format=2
:
       net/http: request canceled while waiting for connection
(Client.Timeout exceeded while
       awaiting headers)

**Comment by battlemidget** [comment] 2018-02-17 18:23
Could possibly be network related, could you try again today?

**Comment by Desmondwong** [comment] 2018-02-19 05:02
Adam,

Thanks, It is working now.  By the way I keep getting this Bad Gateway
error and not sure how to fix it.

desmond is fantastic @ $ kubectl get pods
Error from server (InternalError): an error on the server
("<html>\r\n<head><title>502 Bad Gateway</title></head>\r\n<body
bgcolor=\"white\">\r\n<center><h1>502 Bad
Gateway</h1></center>\r\n<hr><center>nginx/1.10.3
(Ubuntu)</center>\r\n</body>\r\n</html>") has prevented the request from
succeeding (get pods)

**Comment by battlemidget** [comment] 2018-02-19 12:55
Not sure on that, could be wrong kubeconfig? Can you check ~/.kube/ and make sure kubectl uses the correct one?

**Comment by battlemidget** [comment] 2018-02-19 12:56
closing this as original issue is resolved

**Closed by battlemidget** 2018-02-19 12:56 UTC
Labels: bug

**Comment by battlemidget** [comment] 2018-02-25 15:50
Please open a new bug with the requested information. Also, make sure you're running edge, `sudo snap refresh conjure-up --edge`
