### ISSUE TITLE
failed to use 'lxd' for conjure-up

### ISSUE THREAD

**Issue by jameinel** [conjure-up/conjure-up#675] opened 2017-02-14 13:33 UTC
conjure-up/kubernetes-core: [ERROR] conjure-up/kubernetes-core: Showing dialog for exception:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/conjureup/controllers/newcloud/gui.py", line 171, in render
    creds = Schema[app.current_cloud]
KeyError: 'lxd'

While trying to investigate:
https://github.com/conjure-up/conjure-up/issues/674
or
https://bugs.launchpad.net/juju/+bug/1664409

I did 'apt install conjure-up' because I was trying to see how conjure up used to work (rather than using snap install to get the latest conjure-up).

It gave me a list of possible clouds to use, which included "lxd". (probably because I have an 'lxd' defined in ~/.local/share/juju/clouds.yaml). However, when I went to use it, it gave me an error and the above traceback was in ~/.cache/conjure-up/conjure-up.log

It was happy if I did "define new cloud 'localhost'", but having a cloud named 'lxd' made it very unhappy.

$ conjure-up --version
conjure-up 2.1.0

**Comment by battlemidget** [comment] 2017-02-14 13:40
@jameinel Thanks John, this is a dupe of https://github.com/conjure-up/conjure-up/issues/576 which is high on my priority list to get done.

**Comment by battlemidget** [comment] 2017-02-14 13:43
If you want to create a new cloud and use the snap from

```
sudo snap install conjure-up --classic --stable
```

This is using juju 2.0.3 which shows the expected behavior

**Comment by battlemidget** [comment] 2017-02-14 13:45
FYI this is the schema we use for that https://github.com/conjure-up/conjure-up/blob/master/conjureup/models/provider.py 

We'll need to account for those creating their own custom clouds

**Comment by battlemidget** [comment] 2017-03-01 13:04
Going to close this since a bug already exists on this problem

**Closed by battlemidget** 2017-03-01 13:04 UTC
Labels: bug
