### ISSUE TITLE
"Unable to list models: {}".format(sh.stderr.decode('utf8')))

### ISSUE THREAD

**Issue by sergiusens** [conjure-up/conjure-up#574] opened 2017-01-13 07:41 UTC
```
Please either create a new controller using "juju bootstrap" or connect to
another controller that you have been given access to using "juju register".


exception calling callback for <Future at 0x7f64b8c85358 state=finished raised LookupError>
Traceback (most recent call last):
  File "/usr/lib/python3.5/concurrent/futures/_base.py", line 297, in _invoke_callbacks
    callback(self)
  File "/usr/lib/python3/dist-packages/conjureup/controllers/deploy/gui.py", line 69, in _pre_deploy_done
    future.result())))
  File "/usr/lib/python3.5/concurrent/futures/_base.py", line 398, in result
    return self.__get_result()
  File "/usr/lib/python3.5/concurrent/futures/_base.py", line 357, in __get_result
    raise self._exception
  File "/usr/lib/python3/dist-packages/conjureup/controllers/deploy/gui.py", line 61, in _pre_deploy_done
    result = json.loads(future.result().stdout.decode())
  File "/usr/lib/python3.5/concurrent/futures/_base.py", line 398, in result
    return self.__get_result()
  File "/usr/lib/python3.5/concurrent/futures/_base.py", line 357, in __get_result
    raise self._exception
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3/dist-packages/conjureup/controllers/deploy/gui.py", line 38, in _pre_deploy_exec
    app.current_model)['provider-type']
  File "/usr/lib/python3/dist-packages/conjureup/juju.py", line 36, in _decorator
    login(force=True)
  File "/usr/lib/python3/dist-packages/conjureup/juju.py", line 127, in login
    uuid = get_model(app.current_controller, app.current_model)['model-uuid']
  File "/usr/lib/python3/dist-packages/conjureup/juju.py", line 592, in get_model
    models = get_models(controller)['models']
  File "/usr/lib/python3/dist-packages/conjureup/juju.py", line 626, in get_models
    "Unable to list models: {}".format(sh.stderr.decode('utf8')))
LookupError: Unable to list models: error: No controllers registered.

Please either create a new controller using "juju bootstrap" or connect to
another controller that you have been given access to using "juju register".
```

**Comment by mikemccracken** [comment] 2017-01-13 07:45
@sergiusens this looks like you got to the deploy screen without any bootstrapped controllers. 
This shouldn't happen, as any error in bootstrap should have caused conjure-up to show a fatal error dialog. Can you give some more context to how you got here?

**Comment by sergiusens** [comment] 2017-01-13 07:48
@mikemccracken Adam asked me to log just like this as it was enough for him.

This is a vanilla default setup inside a fresh lxd xenial image right after it ends downloading the cloud image when setting up a Core Kubernetes spell

**Comment by mikemccracken** [comment] 2017-01-13 07:50
@sergiusens ok, thanks, I'll check with him.

**Comment by battlemidget** [comment] 2017-02-09 04:17
dupe of #641

**Closed by battlemidget** 2017-02-09 04:17 UTC

**Comment by cr0n-dist0rti0n** [comment] 2017-02-14 07:28
Sorry to post on a closed bug but I am getting the exact same error as above. In addition here is my "[conjure-up.log](https://dl.dropboxusercontent.com/u/25245714/conjure-up.log)". I have:

sudo apt-add-repository ppa:juju/stable
sudo apt-add-repository ppa:conjure-up/next
sudo apt update
sudo apt install conjure-up

So I'm assuming everything should be up to date. Is there a fix for this? Suggestions?
Thanks!!

**Comment by battlemidget** [comment] 2017-02-14 10:34
You'll want to use the snap version, see http://conjure-up.io for details
