### ISSUE TITLE
conjure up stops on hook error even though juju retries

### ISSUE THREAD

**Issue by battlemidget** [conjure-up/conjure-up#601] opened 2017-01-18 14:35 UTC
I installed the Canonical Kubernetes bundle.

During the deployment of the charms, there was a hook error (etcd cluster relation joined error as stuff was starting up). Juju retried the hook and continued ok. But conjure-up gets stuck on the error:

"Oops, there was a problem with your install".... etc.

**Comment by mikemccracken** [comment] 2017-01-18 18:28
dupe of #609

**Closed by mikemccracken** 2017-01-18 18:28 UTC
