### ISSUE TITLE
Waiting for 5 kube-system pods to start

### ISSUE THREAD

**Issue by Matrix-Zhang** [conjure-up/conjure-up#1562] opened 2018-12-18 09:29 UTC
![image](https://user-images.githubusercontent.com/1751829/50144556-7fb9da00-02ea-11e9-8bc3-b8ed0b795c0f.png)

```
/snap/bin/juju --version
2.4.3-bionic-amd64
```

```
/snap/bin/conjure-up --version
conjure-up 2.6.4

/snap/bin/lxc config show
config:
  core.https_address: '[::]'

/snap/bin/lxc version
Client version: 3.8
Server version: 3.8

cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.1 LTS"
```

/snap/bin/lxc config show
/snap/bin/lxc version

[conjure-up.tar.gz](https://github.com/conjure-up/conjure-up/files/2689777/conjure-up.tar.gz)

## Sosreport

Please attach a sosreport:

```
sosreport (version 3.6)

no valid plugins were enabled

```

## What Spell was Selected?

Kubernets

## What provider (aws, maas, localhost, etc)?

```
localhost
```

### MAAS Users
Which version of MAAS?

None

## Commands ran

Please outline what commands were run to install and execute conjure-up:

```
/snap/bin/conjure-up
```

## Additional Information
```
/snap/bin/lxc storage show default
config:
  source: /var/snap/lxd/common/lxd/storage-pools/default
description: ""
name: default
driver: dir
used_by:
- /1.0/containers/juju-88a750-0
- /1.0/containers/juju-88a750-1
- /1.0/containers/juju-88a750-2
- /1.0/containers/juju-88a750-3
- /1.0/containers/juju-88a750-4
- /1.0/containers/juju-88a750-5
- /1.0/containers/juju-88a750-6
- /1.0/containers/juju-88a750-7
- /1.0/containers/juju-88a750-8
- /1.0/containers/juju-88a750-9
- /1.0/containers/juju-a94cd0-0
- /1.0/profiles/default
status: Created
locations:
- none

```

```
/snap/bin/lxc network show lxdbr0
config:
  ipv4.address: 10.199.30.1/24
  ipv4.nat: "true"
  ipv6.address: none
description: ""
name: lxdbr0
type: bridge
used_by:
- /1.0/containers/juju-88a750-0
- /1.0/containers/juju-88a750-1
- /1.0/containers/juju-88a750-2
- /1.0/containers/juju-88a750-3
- /1.0/containers/juju-88a750-4
- /1.0/containers/juju-88a750-5
- /1.0/containers/juju-88a750-6
- /1.0/containers/juju-88a750-7
- /1.0/containers/juju-88a750-8
- /1.0/containers/juju-88a750-9
- /1.0/containers/juju-a94cd0-0
managed: true
status: Created
locations:
- none

```

**Comment by battlemidget** [comment] 2018-12-18 15:50
Is that deployment still up? Can you run https://github.com/juju-solutions/cdk-field-agent and attach the results here?

**Comment by Matrix-Zhang** [comment] 2018-12-19 08:19
i have retried with new deployment, and the result is similar, just become to "Waiting for 6 kube-system pods to start"

[results-2018-12-19-16-13-34.tar.gz](https://github.com/conjure-up/conjure-up/files/2693864/results-2018-12-19-16-13-34.tar.gz)

**Comment by battlemidget** [comment] 2018-12-19 11:31
@Cynerva @hyperbolic2346 any ideas here? I can't reproduce this

**Comment by Cynerva** [comment] 2018-12-19 14:20
The kubernetes-worker machines are not able to pull images from k8s.gcr.io:

```
Failed create pod sandbox: rpc error: code = Unknown desc = failed pulling image "k8s.gcr.io/pause:3.1": Error response from daemon: Get https://k8s.gcr.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
```

Is there a firewall in this environment that could be filtering the traffic?

**Comment by battlemidget** [comment] 2018-12-19 19:46
Closing as not a bug

**Closed by battlemidget** 2018-12-19 19:46 UTC
