### ISSUE TITLE
snap install conjure-up --classic --stable fails in lxd privileged container

### ISSUE THREAD

**Issue by gaetanquentin** [conjure-up/conjure-up#689] opened 2017-02-17 08:59 UTC
since conjure-up ubuntu package (16.04) has been replaced by snaps, i cannot install anymore conjure-up in a lxd container:

snap install conjure-up --classic --stable
output:
error: cannot perform the following tasks:
- Mount snap "core" (1079) ([start snap-core-1079.mount] failed with exit status 1: Job for snap-core-1079.mount failed. See "systemctl status snap-core-1079.mount" and "journalctl -xe" for details.
)
root@openstack:~# systemctl status snap-core-1079.mount
● snap-core-1079.mount - Mount unit for core
   Loaded: loaded (/etc/systemd/system/snap-core-1079.mount; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Fri 2017-02-17 08:52:32 UTC; 17s ago
    Where: /snap/core/1079
     What: /var/lib/snapd/snaps/core_1079.snap
  Process: 3973 ExecMount=/bin/mount /var/lib/snapd/snaps/core_1079.snap /snap/core/1079 -t squashfs (code=exited, status=32)

Feb 17 08:52:32 openstack systemd[1]: Mounting Mount unit for core...
Feb 17 08:52:32 openstack mount[3973]: mount: /snap/core/1079: mount failed: Unknown error -1
Feb 17 08:52:32 openstack systemd[1]: snap-core-1079.mount: Mount process exited, code=exited status=32
Feb 17 08:52:32 openstack systemd[1]: Failed to mount Mount unit for core.
Feb 17 08:52:32 openstack systemd[1]: snap-core-1079.mount: Unit entered failed state.

root@openstack:~# journalctl -xe 
Feb 17 08:52:32 openstack systemd[1]: Failed to reset devices.list on /init.scope: Operation not permitted
Feb 17 08:52:32 openstack systemd[1]: Failed to reset devices.list on /user.slice: Operation not permitted
Feb 17 08:52:32 openstack systemd[1]: Failed to reset devices.list on /system.slice/rsyslog.service: Operation not permitted
Feb 17 08:52:32 openstack systemd[1]: Failed to reset devices.list on /system.slice/lvm2-monitor.service: Operation not permitted
Feb 17 08:52:32 openstack systemd[1]: Failed to reset devices.list on /system.slice/proc-meminfo.mount: Operation not permitted
Feb 17 08:52:32 openstack systemd[1]: Failed to reset devices.list on /system.slice/dev-.lxc-sys.mount: Operation not permitted
Feb 17 08:52:32 openstack systemd[1]: Failed to reset devices.list on /system.slice/lxd-containers.service: Operation not permitted
Feb 17 08:52:32 openstack systemd[1]: Failed to reset devices.list on /system.slice/dev-mqueue.mount: Operation not permitted
Feb 17 08:52:32 openstack systemd[1]: Failed to reset devices.list on /system.slice/dev-mem.mount: Operation not permitted
Feb 17 08:52:32 openstack systemd[1]: Failed to reset devices.list on /system.slice/-.mount: Operation not permitted
Feb 17 08:52:32 openstack systemd[1]: Failed to reset devices.list on /system.slice/rc-local.service: Operation not permitted
Feb 17 08:52:32 openstack systemd[1]: Failed to reset devices.list on /system.slice/snapd.service: Operation not permitted
Feb 17 08:52:32 openstack systemd[1]: Failed to reset devices.list on /system.slice/cron.service: Operation not permitted
Feb 17 08:52:32 openstack mount[3973]: mount: /snap/core/1079: mount failed: Unknown error -1
Feb 17 08:52:32 openstack systemd[1]: Failed to reset devices.list on /system.slice/proc-sysrq\x2dtrigger.mount: Operation not permitted
Feb 17 08:52:32 openstack systemd[1]: Failed to reset devices.list on /system.slice/apparmor.service: Operation not permitted
Feb 17 08:52:32 openstack systemd[1]: Failed to reset devices.list on /system.slice/sys-devices-virtual-net.mount: Operation not permitted
Feb 17 08:52:32 openstack systemd[1]: Failed to reset devices.list on /system.slice/systemd-user-sessions.service: Operation not permitted
Feb 17 08:52:32 openstack systemd[1]: Failed to reset devices.list on /system.slice/iscsid.service: Operation not permitted
Feb 17 08:52:32 openstack systemd[1]: Failed to reset devices.list on /system.slice/ondemand.service: Operation not permitted
Feb 17 08:52:32 openstack systemd[1]: Failed to reset devices.list on /system.slice/dev-net-tun.mount: Operation not permitted
Feb 17 08:52:32 openstack systemd[1]: Failed to reset devices.list on /system.slice/systemd-journald.service: Operation not permitted
Feb 17 08:52:32 openstack systemd[1]: Failed to reset devices.list on /system.slice/proc-cpuinfo.mount: Operation not permitted
Feb 17 08:52:32 openstack systemd[1]: Failed to reset devices.list on /system.slice/sys-kernel-debug-tracing.mount: Operation not permitted
Feb 17 08:52:32 openstack systemd[1]: Failed to reset devices.list on /system.slice/resolvconf.service: Operation not permitted
Feb 17 08:52:32 openstack systemd[1]: Failed to reset devices.list on /system.slice/sys-kernel-debug.mount: Operation not permitted
Feb 17 08:52:32 openstack systemd[1]: Failed to reset devices.list on /system.slice/system-getty.slice: Operation not permitted
Feb 17 08:52:32 openstack systemd[1]: Failed to reset devices.list on /system.slice/proc-uptime.mount: Operation not permitted
Feb 17 08:52:32 openstack systemd[1]: Failed to reset devices.list on /system.slice/dev-fuse.mount: Operation not permitted
Feb 17 08:52:32 openstack systemd[1]: Failed to reset devices.list on /system.slice/mdadm.service: Operation not permitted
Feb 17 08:52:32 openstack systemd[1]: Failed to reset devices.list on /system.slice/systemd-logind.service: Operation not permitted
Feb 17 08:52:32 openstack systemd[1]: Failed to reset devices.list on /system.slice/cloud-final.service: Operation not permitted
Feb 17 08:52:32 openstack systemd[1]: Failed to reset devices.list on /system.slice/networking.service: Operation not permitted
Feb 17 08:52:32 openstack systemd[1]: Failed to reset devices.list on /system.slice/open-iscsi.service: Operation not permitted
Feb 17 08:52:32 openstack systemd[1]: Failed to reset devices.list on /system.slice/console-getty.service: Operation not permitted
Feb 17 08:52:32 openstack systemd[1]: Failed to reset devices.list on /system.slice/cloud-init-local.service: Operation not permitted
Feb 17 08:52:32 openstack systemd[1]: Failed to reset devices.list on /system.slice/systemd-random-seed.service: Operation not permitted
Feb 17 08:52:32 openstack systemd[1]: Failed to reset devices.list on /system.slice/apport.service: Operation not permitted
Feb 17 08:52:32 openstack systemd[1]: Failed to reset devices.list on /system.slice/dbus.service: Operation not permitted
Feb 17 08:52:32 openstack systemd[1]: Failed to reset devices.list on /system.slice/dev-hugepages.mount: Operation not permitted
Feb 17 08:52:32 openstack systemd[1]: Failed to reset devices.list on /system.slice/proc-stat.mount: Operation not permitted
Feb 17 08:52:32 openstack systemd[1]: Failed to reset devices.list on /system.slice/cloud-config.service: Operation not permitted
Feb 17 08:52:32 openstack systemd[1]: Failed to reset devices.list on /system.slice/accounts-daemon.service: Operation not permitted
Feb 17 08:52:32 openstack systemd[1]: Failed to reset devices.list on /system.slice/irqbalance.service: Operation not permitted
Feb 17 08:52:32 openstack systemd[1]: Failed to reset devices.list on /system.slice/systemd-update-utmp.service: Operation not permitted
Feb 17 08:52:32 openstack systemd[1]: Failed to reset devices.list on /system.slice/proc-swaps.mount: Operation not permitted
Feb 17 08:52:32 openstack systemd[1]: Failed to reset devices.list on /system.slice/var-lib-lxcfs.mount: Operation not permitted
Feb 17 08:52:32 openstack systemd[1]: Failed to reset devices.list on /system.slice/atd.service: Operation not permitted
Feb 17 08:52:32 openstack systemd[1]: Failed to reset devices.list on /system.slice/ufw.service: Operation not permitted
Feb 17 08:52:32 openstack systemd[1]: Failed to reset devices.list on /system.slice/proc-diskstats.mount: Operation not permitted
Feb 17 08:52:32 openstack systemd[1]: Failed to reset devices.list on /system.slice/dev-.lxd\x2dmounts.mount: Operation not permitted
Feb 17 08:52:32 openstack systemd[1]: Failed to reset devices.list on /system.slice/systemd-journal-flush.service: Operation not permitted
Feb 17 08:52:32 openstack systemd[1]: Failed to reset devices.list on /system.slice/dev-lxd.mount: Operation not permitted
Feb 17 08:52:32 openstack systemd[1]: Failed to reset devices.list on /system.slice/polkitd.service: Operation not permitted
Feb 17 08:52:32 openstack systemd[1]: Failed to reset devices.list on /system.slice/systemd-tmpfiles-setup.service: Operation not permitted
Feb 17 08:52:32 openstack systemd[1]: Failed to reset devices.list on /system.slice/sys-fs-fuse-connections.mount: Operation not permitted
Feb 17 08:52:32 openstack systemd[1]: Failed to reset devices.list on /system.slice/ssh.service: Operation not permitted
Feb 17 08:52:32 openstack systemd[1]: Failed to reset devices.list on /system.slice/cloud-init.service: Operation not permitted
Feb 17 08:52:32 openstack systemd[1]: Failed to reset devices.list on /system.slice/dev-.lxc-proc.mount: Operation not permitted
Feb 17 08:52:32 openstack systemd[1]: Failed to reset devices.list on /system.slice/proc-sys-net.mount: Operation not permitted
Feb 17 08:52:32 openstack systemd[1]: Failed to reset devices.list on /system.slice/proc-sys-fs-binfmt_misc.mount: Operation not permitted
Feb 17 08:52:32 openstack systemd[1]: snap-core-1079.mount: Mount process exited, code=exited status=32
Feb 17 08:52:32 openstack systemd[1]: Failed to mount Mount unit for core.
-- Subject: Unit snap-core-1079.mount has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit snap-core-1079.mount has failed.
-- 
-- The result is failed.
Feb 17 08:52:32 openstack systemd[1]: snap-core-1079.mount: Unit entered failed state.
Feb 17 08:52:32 openstack /usr/lib/snapd/snapd[2744]: task.go:303: DEBUG: 2017-02-17T08:52:32Z ERROR [start snap-core-1079.mount] failed with exit status 1: Job for snap-core-1079.mount failed. See "systemctl st
Feb 17 08:52:32 openstack /usr/lib/snapd/snapd[2744]: taskrunner.go:353: DEBUG: Running task 21 on Undo: Download snap "core" (1079) from channel "stable"
Feb 17 08:53:24 openstack systemd[1]: Failed to reset devices.list on /system.slice/systemd-tmpfiles-clean.service: Operation not permitted
Feb 17 08:53:24 openstack systemd[1]: Starting Cleanup of Temporary Directories...
-- Subject: Unit systemd-tmpfiles-clean.service has begun start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit systemd-tmpfiles-clean.service has begun starting up.
Feb 17 08:53:24 openstack systemd-tmpfiles[3976]: [/usr/lib/tmpfiles.d/var.conf:14] Duplicate line for path "/var/log", ignoring.
Feb 17 08:53:24 openstack systemd[1]: Started Cleanup of Temporary Directories.
-- Subject: Unit systemd-tmpfiles-clean.service has finished start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit systemd-tmpfiles-clean.service has finished starting up.
-- 
-- The start-up result is done.

**Comment by battlemidget** [comment] 2017-02-17 13:44
Dupe of https://github.com/conjure-up/conjure-up/issues/688

**Closed by battlemidget** 2017-02-17 13:44 UTC
