### ISSUE TITLE
rabbitmq-server/0: hook failed

### ISSUE THREAD

**Issue by tglovernuppy** [conjure-up/conjure-up#489] opened 2016-10-12 03:31 UTC
#### Environment
* Juju: **2.0-rc3-0ubuntu1~16.04.1~juju1**
* conjure-up: **2.0.1-0~201610061938~ubuntu16.04.1**

#### Problem
I got the following "hook failed" error on rabbitmq-server/0 in the deployment phase.

```
hook failed: "amqp-relation-changed" for nova-compute:amqp
```

Looking at the juju log of rabbitmq-server/0, I found these lines that shows the error:

```
ubuntu@juju-84f95a-15$ sudo less +F /var/log/juju/unit-rabbitmq-server-0.log
...
2016-10-11 01:29:59 DEBUG juju-log amqp:27: Hardening function 'install'
2016-10-11 01:29:59 DEBUG juju-log amqp:27: Hardening function 'upgrade_charm'
2016-10-11 01:29:59 DEBUG juju-log amqp:27: Hardening function 'config_changed'
2016-10-11 01:29:59 DEBUG juju-log amqp:27: Hardening function 'update_status'
2016-10-11 01:30:00 INFO amqp-relation-changed Error: unable to connect to node rabbit@ubuntu: nodedown
2016-10-11 01:30:00 INFO amqp-relation-changed
2016-10-11 01:30:00 INFO amqp-relation-changed DIAGNOSTICS
2016-10-11 01:30:00 INFO amqp-relation-changed ===========
2016-10-11 01:30:00 INFO amqp-relation-changed
2016-10-11 01:30:00 INFO amqp-relation-changed attempted to contact: [rabbit@ubuntu]
2016-10-11 01:30:00 INFO amqp-relation-changed
2016-10-11 01:30:00 INFO amqp-relation-changed rabbit@ubuntu:
2016-10-11 01:30:00 INFO amqp-relation-changed   * unable to connect to epmd (port 4369) on ubuntu: nxdomain (non-existing domain)
2016-10-11 01:30:00 INFO amqp-relation-changed
2016-10-11 01:30:00 INFO amqp-relation-changed
2016-10-11 01:30:00 INFO amqp-relation-changed current node details:
2016-10-11 01:30:00 INFO amqp-relation-changed - node name: 'rabbitmq-cli-20529@juju-84f95a-15'
2016-10-11 01:30:00 INFO amqp-relation-changed - home dir: /var/lib/rabbitmq
2016-10-11 01:30:00 INFO amqp-relation-changed - cookie hash: Grmb/HfpexA0abUh5/acVQ==
2016-10-11 01:30:00 INFO amqp-relation-changed
2016-10-11 01:30:00 DEBUG juju-log amqp:27: Command '['/usr/sbin/rabbitmqctl', 'list_vhosts']' returned non-zero exit status 2
2016-10-11 01:30:00 DEBUG juju-log amqp:27: Running ['/usr/sbin/rabbitmqctl', 'add_vhost', u'openstack']
2016-10-11 01:30:00 INFO amqp-relation-changed Error: unable to connect to node rabbit@ubuntu: nodedown
2016-10-11 01:30:00 INFO amqp-relation-changed
2016-10-11 01:30:00 INFO amqp-relation-changed DIAGNOSTICS
2016-10-11 01:30:00 INFO amqp-relation-changed ===========
2016-10-11 01:30:00 INFO amqp-relation-changed
2016-10-11 01:30:00 INFO amqp-relation-changed attempted to contact: [rabbit@ubuntu]
2016-10-11 01:30:00 INFO amqp-relation-changed
2016-10-11 01:30:00 INFO amqp-relation-changed rabbit@ubuntu:
2016-10-11 01:30:00 INFO amqp-relation-changed   * unable to connect to epmd (port 4369) on ubuntu: nxdomain (non-existing domain)
2016-10-11 01:30:00 INFO amqp-relation-changed
2016-10-11 01:30:00 INFO amqp-relation-changed
2016-10-11 01:30:00 INFO amqp-relation-changed current node details:
2016-10-11 01:30:00 INFO amqp-relation-changed - node name: 'rabbitmq-cli-20656@juju-84f95a-15'
2016-10-11 01:30:00 INFO amqp-relation-changed - home dir: /var/lib/rabbitmq
2016-10-11 01:30:00 INFO amqp-relation-changed - cookie hash: Grmb/HfpexA0abUh5/acVQ==
2016-10-11 01:30:00 INFO amqp-relation-changed
2016-10-11 01:30:01 INFO amqp-relation-changed Segmentation fault (core dumped)
2016-10-11 01:30:01 INFO amqp-relation-changed Traceback (most recent call last):
2016-10-11 01:30:01 INFO amqp-relation-changed   File "/var/lib/juju/agents/unit-rabbitmq-server-0/charm/hooks/amqp-relation-changed", line 765, in <module>
2016-10-11 01:30:01 INFO amqp-relation-changed     hooks.execute(sys.argv)
2016-10-11 01:30:01 INFO amqp-relation-changed   File "/var/lib/juju/agents/unit-rabbitmq-server-0/charm/hooks/charmhelpers/core/hookenv.py", line 715, in execute
2016-10-11 01:30:01 INFO amqp-relation-changed     self._hooks[hook_name]()
2016-10-11 01:30:01 INFO amqp-relation-changed   File "/var/lib/juju/agents/unit-rabbitmq-server-0/charm/hooks/amqp-relation-changed", line 212, in amqp_changed
2016-10-11 01:30:01 INFO amqp-relation-changed     admin=settings.get('admin', False))
2016-10-11 01:30:01 INFO amqp-relation-changed   File "/var/lib/juju/agents/unit-rabbitmq-server-0/charm/hooks/amqp-relation-changed", line 153, in configure_amqp
2016-10-11 01:30:01 INFO amqp-relation-changed     rabbit.create_vhost(vhost)
2016-10-11 01:30:01 INFO amqp-relation-changed   File "/var/lib/juju/agents/unit-rabbitmq-server-0/charm/hooks/rabbit_utils.py", line 177, in create_vhost
2016-10-11 01:30:01 INFO amqp-relation-changed     rabbitmqctl('add_vhost', vhost)
2016-10-11 01:30:01 INFO amqp-relation-changed   File "/var/lib/juju/agents/unit-rabbitmq-server-0/charm/hooks/rabbit_utils.py", line 321, in rabbitmqctl
2016-10-11 01:30:01 INFO amqp-relation-changed     subprocess.check_call(cmd)
2016-10-11 01:30:01 INFO amqp-relation-changed   File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
2016-10-11 01:30:01 INFO amqp-relation-changed     raise CalledProcessError(retcode, cmd)
2016-10-11 01:30:01 INFO amqp-relation-changed subprocess.CalledProcessError: Command '['/usr/sbin/rabbitmqctl', 'add_vhost', u'openstack']' returned non-zero exit sta
tus 139
2016-10-11 01:30:01 ERROR juju.worker.uniter.operation runhook.go:107 hook "amqp-relation-changed" failed: exit status 1
``` 

The problem was easily solved by modifying the last line of rabbitmq-server's configuration file `/etc/rabbitmq/rabbitmq-env.conf`

**FROM**

```
RABBITMQ_NODENAME=rabbit@ubuntu
```

**TO**

```
RABBITMQ_NODENAME=rabbit@juju-84f95a-15
```

and then restart the service by `sudo service rabbitmq-server restart`.

How is it possible to have the proper `RABBITMQ_NODENAME` set by default so that I do not need to modify and fix the error?

**Comment by mikemccracken** [comment] 2016-10-12 03:52
Hi @tglovernuppy - is this with the openstack-novalxd spell?

If so, then this is a known intermittent bug caused by an interaction between juju, LXD, cloud-init, and the rabbitmq charm. It is a race between rabbit and the juju tasks that will set the hostname on a container. It's lasted this long, I believe, because programs that expect to immediately resolve their hostname are rare.

My apologies for the problem.

It's being tracked in a couple of places:

## LXD and Cloud-init

It looks like lxd will eventually grow a permanent solution to this issue:
https://bugs.launchpad.net/ubuntu/+source/cloud-init/+bug/1600766

## Juju

I know of at least these three related bugs:

  * https://bugs.launchpad.net/juju/+bug/1587503
  * https://bugs.launchpad.net/juju/+bug/1623480
  * https://bugs.launchpad.net/juju/+bug/1593185

A couple of these are marked fix-committed and were targeted at rc3, so either they didn't quite fix this, or it will be in the next RC.

Unfortunately I don't know of a great workaround for this, but since it's a race, you could try something like deploying rabbitmq-server first by itself, to see if a lightly loaded system would behave better. To try this, on the screen where the apps are listed with 'configure' buttons, just 'deploy' the one and wait, it will be starting the container and running juju hooks in the background. A second tab open with `watch juju status` might be useful here. If that deployment works, then you can probably deploy the rest with no issue.

**Comment by tglovernuppy** [comment] 2016-10-12 04:27
Thank you for your prompt reply, @mikemccracken.

> is this with the openstack-novalxd spell?

Yes, exactly.

Thanks a lot for the detailed descriptions on how the problem is caused and useful advice about them. I did not know this issue was already known and it had been tracked. I apologize for creating a new issue on the known issue.

I will close this as the workaround is provided.
Thank you.

**Comment by mikemccracken** [comment] 2016-10-12 04:42
Hi, no need for an apology. Please feel free to reopen this issue if you
continue to see problems.

**Comment by battlemidget** [comment] 2016-10-12 10:29
want to document this

**Closed** 2016-10-12 12:09 UTC
Labels: documentation

**Comment by battlemidget** [comment] 2016-10-12 19:27
FYI, this should be addressed in the next couple of days when new cloud images roll out.

**Comment by tglovernuppy** [comment] 2016-10-13 03:28
Thank you for your documentation and the information. I appreciate your quick response.
