### ISSUE TITLE
running pre-deployment tasks non-responsive

### ISSUE THREAD

**Issue by battlemidget** [conjure-up/conjure-up#602] opened 2017-01-18 14:37 UTC
I did 'conjure-up kubernetes', it got through the bootstrapping of Juju, and all the way to:
  Running pre-deployment tasks.

However, on that screen there is no other text or spinning icon. So it just has the banner at the top, and the single line above.
I went to resize the window to take a screenshot, and it destroyed the display so I now only have that one line shown. It did not resize or do anything else.

Looking at "juju status" I do see several applications starting:
$ juju status
Model Controller Cloud/Region Version
conjure-up teal localhost/localhost 2.1-rc1.1

App Version Status Scale Charm Store Rev OS Notes
easyrsa waiting 0/1 easyrsa jujucharms 5 ubuntu
etcd waiting 0/3 etcd jujucharms 21 ubuntu
flannel waiting 0 flannel jujucharms 7 ubuntu

Unit Workload Agent Machine Public address Ports Message
easyrsa/0 waiting allocating 0 10.14.247.100 waiting for machine
etcd/0 waiting allocating 1 10.14.247.83 waiting for machine
etcd/1 waiting allocating 2 10.14.247.122 waiting for machine
etcd/2 waiting allocating 3 waiting for machine

Machine State DNS Inst id Series AZ
0 pending 10.14.247.100 juju-c2c882-0 xenial
1 pending 10.14.247.83 juju-c2c882-1 xenial
2 pending 10.14.247.122 juju-c2c882-2 xenial
3 pending pending xenial

Relation Provides Consumes Type
cluster etcd etcd peer

$ lxc list
+---------------+---------+----------------------+------+------------+-----------+
| NAME | STATE | IPV4 | IPV6 | TYPE | SNAPSHOTS |
+---------------+---------+----------------------+------+------------+-----------+
| juju-ba6c85-0 | RUNNING | 10.14.247.99 (eth0) | | PERSISTENT | 0 |
+---------------+---------+----------------------+------+------------+-----------+
| juju-c2c882-0 | RUNNING | 10.14.247.100 (eth0) | | PERSISTENT | 0 |
+---------------+---------+----------------------+------+------------+-----------+
| juju-c2c882-1 | RUNNING | 10.14.247.83 (eth0) | | PERSISTENT | 0 |
+---------------+---------+----------------------+------+------------+-----------+
| juju-c2c882-2 | RUNNING | 10.14.247.122 (eth0) | | PERSISTENT | 0 |
+---------------+---------+----------------------+------+------------+-----------+

However, conjure-up is still hung.

Additional:
Doing a ^C on conjure-up gave me these 2 tracebacks:
$ conjure-up kubernetes
Exception in ev.run():
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/ubuntui/ev.py", line 83, in run
    cls.loop.run()
  File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 278, in run
    self._run()
  File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 376, in _run
    self.event_loop.run()
  File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 1326, in run
    self._loop.run_forever()
  File "/usr/lib/python3.5/asyncio/base_events.py", line 345, in run_forever
    self._run_once()
  File "/usr/lib/python3.5/asyncio/base_events.py", line 1312, in _run_once
    handle._run()
  File "/usr/lib/python3.5/asyncio/events.py", line 125, in _run
    self._callback(*self._args)
  File "/usr/lib/python3/dist-packages/conjureup/ui/views/deploystatus.py", line 31, in _refresh_nodes_on_main_thread
    status = model_status()
  File "/usr/lib/python3/dist-packages/conjureup/juju.py", line 37, in _decorator
    return f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/conjureup/api/models.py", line 42, in model_status
    return juju.CLIENT.Client(request="FullStatus")
  File "/usr/lib/python3/dist-packages/macumba/v2.py", line 119, in _request
    'Params': params})
  File "/usr/lib/python3/dist-packages/macumba/v2.py", line 130, in call
    return self.receive(req_id, timeout)
  File "/usr/lib/python3/dist-packages/macumba/api.py", line 131, in receive
    time.sleep(0.1)
KeyboardInterrupt
Traceback (most recent call last):
  File "/usr/bin/conjure-up", line 9, in <module>
    load_entry_point('conjure-up==2.1.0', 'console_scripts', 'conjure-up')()
  File "/usr/lib/python3/dist-packages/conjureup/app.py", line 321, in main
    EventLoop.run()
  File "/usr/lib/python3/dist-packages/ubuntui/ev.py", line 83, in run
    cls.loop.run()
  File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 278, in run
    self._run()
  File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 376, in _run
    self.event_loop.run()
  File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 1326, in run
    self._loop.run_forever()
  File "/usr/lib/python3.5/asyncio/base_events.py", line 345, in run_forever
    self._run_once()
  File "/usr/lib/python3.5/asyncio/base_events.py", line 1312, in _run_once
    handle._run()
  File "/usr/lib/python3.5/asyncio/events.py", line 125, in _run
    self._callback(*self._args)
  File "/usr/lib/python3/dist-packages/conjureup/ui/views/deploystatus.py", line 31, in _refresh_nodes_on_main_thread
    status = model_status()
  File "/usr/lib/python3/dist-packages/conjureup/juju.py", line 37, in _decorator
    return f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/conjureup/api/models.py", line 42, in model_status
    return juju.CLIENT.Client(request="FullStatus")
  File "/usr/lib/python3/dist-packages/macumba/v2.py", line 119, in _request
    'Params': params})
  File "/usr/lib/python3/dist-packages/macumba/v2.py", line 130, in call
    return self.receive(req_id, timeout)
  File "/usr/lib/python3/dist-packages/macumba/api.py", line 131, in receive
    time.sleep(0.1)
KeyboardInterrupt

It didn't return control to Bash, and when I went back and killed the Juju Controller, I then also got:
exception calling callback for <Future at 0x7f37d58136d8 state=finished raised ConnectionClosedError>
Traceback (most recent call last):
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3/dist-packages/conjureup/juju.py", line 37, in _decorator
    return f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/conjureup/juju.py", line 419, in _deploy_async
    params={"url": service.csid.as_str()})
  File "/usr/lib/python3/dist-packages/macumba/v2.py", line 119, in _request
    'Params': params})
  File "/usr/lib/python3/dist-packages/macumba/v2.py", line 130, in call
    return self.receive(req_id, timeout)
  File "/usr/lib/python3/dist-packages/macumba/api.py", line 129, in receive
    res = self.conn.do_receive(request_id)
  File "/usr/lib/python3/dist-packages/macumba/ws.py", line 75, in do_receive
    raise ConnectionClosedError
macumba.errors.ConnectionClosedError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/concurrent/futures/_base.py", line 297, in _invoke_callbacks
    callback(self)
  File "/usr/lib/python3/dist-packages/conjureup/async.py", line 29, in cb
    exc_callback(e)
  File "/usr/lib/python3/dist-packages/conjureup/controllers/deploy/gui.py", line 29, in _handle_exception
    track_exception(exc.args[0])
IndexError: tuple index out of range

At which point I *did* get the bash prompt again. Hopefully one of those tracebacks are useful.

**Comment by mikemccracken** [comment] 2017-01-18 18:22
I think this is a dupe of #541 -- @battlemidget any chance you have the original bug filer's contact?

**Closed by mikemccracken** 2017-01-18 18:22 UTC
