### ISSUE TITLE
Automate the debug info gathering process?

### ISSUE THREAD

**Issue by ktsakalozos** [conjure-up/conjure-up#1360] opened 2018-03-09 08:37 UTC
At the moment filing an issue would require a few manual steps. It would be nice to have a tool to gather all the info needed to open an issue.

Thanks

**Comment by battlemidget** [comment] 2018-03-09 14:10
Dupe of https://github.com/conjure-up/conjure-up/issues/1207

**Closed by battlemidget** 2018-03-09 14:10 UTC
