### ISSUE TITLE
Localhost cluster fails after restart

### ISSUE THREAD

**Issue by gonfva-bcl** [conjure-up/conjure-up#1448] opened 2018-06-04 14:43 UTC
## Report

Thank you for trying **conjure-up**! Before reporting a bug please make sure you've gone through this checklist:

- [ X ] Is this problem already documented at https://docs.ubuntu.com/conjure-up/en/troubleshoot#common-spell-problems
No
- [ X ] Is conjure-up running inside a virtual machine?
No
- [ X ] Is this problem reproducible with `sudo snap refresh conjure-up --edge`?
Yes

## Please provide the output of the following commands

```
$ which juju

/snap/bin/juju
$ juju version
2.3.8-bionic-amd64

$which conjure-up
/snap/bin/conjure-up
$conjure-up --version
conjure-up 2.5.7

$ which lxc
/snap/bin/lxc
$ /snap/bin/lxc config show
config:
  core.https_address: '[::]'
$ /snap/bin/lxc version
Client version: 3.1
Server version: 3.1

$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04 LTS"
```
**Yes it's Ubuntu 18.04**

Please attach tarball of **~/.cache/conjure-up**:

```
tar cvzf conjure-up.tar.gz ~/.cache/conjure-up
```
[conjure-up.tar.gz](https://github.com/conjure-up/conjure-up/files/2068685/conjure-up.tar.gz)

## What Spell was Selected?

Both canonical-kubernetes and kubernetes-core exhibit the same issue

## What provider (aws, maas, localhost, etc)?

localhost

## Commands ran

$ conjure-up kubernetes-core localhost
[...]
$ $ juju status
```
Model                        Controller                Cloud/Region         Version  SLA
conjure-kubernetes-core-786  conjure-up-localhost-7fa  localhost/localhost  2.3.8    unsupported

App                Version  Status   Scale  Charm              Store       Rev  OS      Notes
easyrsa            3.0.1    active       1  easyrsa            jujucharms   44  ubuntu  
etcd               3.2.9    active       1  etcd               jujucharms   87  ubuntu  
flannel            0.9.1    active       2  flannel            jujucharms   59  ubuntu  
kubernetes-master  1.10.3   waiting      1  kubernetes-master  jujucharms  113  ubuntu  exposed
kubernetes-worker  1.10.3   waiting      1  kubernetes-worker  jujucharms  128  ubuntu  exposed

Unit                  Workload  Agent      Machine  Public address  Ports     Message
easyrsa/0*            active    idle       0/lxd/0  10.0.216.26               Certificate Authority connected.
etcd/0*               active    executing  0        10.134.7.14     2379/tcp  Healthy with 1 known peer
kubernetes-master/0*  waiting   executing  0        10.134.7.14     6443/tcp  Waiting for kube-system pods to start
  flannel/0*          active    idle                10.134.7.14               Flannel subnet 10.1.85.1/24
kubernetes-worker/0*  waiting   executing  1        10.134.7.8                Waiting for kubelet,kube-proxy to start.
  flannel/1           active    idle                10.134.7.8                Flannel subnet 10.1.82.1/24

Machine  State    DNS          Inst id              Series  AZ  Message
0        started  10.134.7.14  juju-a1ae2d-0        xenial      Running
0/lxd/0  started  10.0.216.26  juju-a1ae2d-0-lxd-0  xenial      Container started
1        started  10.134.7.8   juju-a1ae2d-1        xenial      Running
```
$ sudo reboot
[...]
$ juju status
```
Model                        Controller                Cloud/Region         Version  SLA
conjure-kubernetes-core-786  conjure-up-localhost-7fa  localhost/localhost  2.3.8    unsupported

App                Version  Status   Scale  Charm              Store       Rev  OS      Notes
easyrsa            3.0.1    active       1  easyrsa            jujucharms   44  ubuntu  
etcd               n/a      error        1  etcd               jujucharms   87  ubuntu  
flannel            0.9.1    waiting      2  flannel            jujucharms   59  ubuntu  
kubernetes-master  1.10.3   error        1  kubernetes-master  jujucharms  113  ubuntu  exposed
kubernetes-worker  1.10.3   error        1  kubernetes-worker  jujucharms  128  ubuntu  exposed

Unit                  Workload  Agent  Machine  Public address  Ports           Message
easyrsa/0*            active    idle   0/lxd/0  10.0.216.26                     Certificate Authority connected.
etcd/0*               error     idle   0        10.134.7.14     2379/tcp        hook failed: "config-changed"
kubernetes-master/0*  error     idle   0        10.134.7.14     6443/tcp        hook failed: "config-changed"
  flannel/0*          waiting   idle            10.134.7.14                     Waiting for Flannel
kubernetes-worker/0*  error     idle   1        10.134.7.8      80/tcp,443/tcp  hook failed: "config-changed"
  flannel/1           waiting   idle            10.134.7.8                      Waiting for Flannel

Machine  State    DNS          Inst id              Series  AZ  Message
0        started  10.134.7.14  juju-a1ae2d-0        xenial      Running
0/lxd/0  started  10.0.216.26  juju-a1ae2d-0-lxd-0  xenial      Container started
```
## Additional Information

Similarly to https://github.com/conjure-up/conjure-up/issues/1392#issuecomment-389482224 it only appears after reboot
Also similar symptoms
https://github.com/juju-solutions/bundle-canonical-kubernetes/issues/357
But 
https://github.com/juju-solutions/bundle-canonical-kubernetes/issues/357#issuecomment-316542831
doesn't help
And
https://github.com/juju-solutions/layer-etcd/pull/108
didn't solve

**Comment by battlemidget** [comment] 2018-06-04 16:03
Whats your `lxc storage list` look like? Make sure you are using `dir` as the storage backend and not btrfs or zfs.

**Comment by gonfva** [comment] 2018-06-04 16:06
```
$ lxc storage list
+------------+-------------+--------+------------------------------------------------+---------+
|    NAME    | DESCRIPTION | DRIVER |                     SOURCE                     | USED BY |
+------------+-------------+--------+------------------------------------------------+---------+
| default    |             | dir    | /var/snap/lxd/common/lxd/storage-pools/default | 4       |
+------------+-------------+--------+------------------------------------------------+---------+
| juju-btrfs |             | btrfs  | /var/snap/lxd/common/lxd/disks/juju-btrfs.img  | 0       |
+------------+-------------+--------+------------------------------------------------+---------+
| juju-zfs   |             | zfs    | /var/snap/lxd/common/lxd/disks/juju-zfs.img    | 0       |
+------------+-------------+--------+------------------------------------------------+---------+
```

**Comment by battlemidget** [comment] 2018-06-04 16:08
Yea juju is trying to use zfs/btrfs and failing.

**Comment by gonfva** [comment] 2018-06-05 13:42
Hi, thank you. 

I know very little about all these technologies, so apologies in advance.

1)I deleted the existing cluster
2)I deleted btrfs and zfs storage pools (` lxc storage delete juju-zfs`` lxc storage delete juju-btrfs`)
3)Recreated the "cluster" with `conjure-up kubernetes-core localhost`  (quotes because it's localhost)
4)The "cluster" comes up fine
5)The btrfs and zfs storage pools have appeared again. I delete them again and reboot.
6)After reboot, the "cluster" shows the problem mentioned before.

I couldn't find any option to choose dir. Is it something I should be doing before launching the cluster?

**Comment by battlemidget** [comment] 2018-06-05 17:43
Whats the output of `lxc profile show default`?

**Comment by gonfva** [comment] 2018-06-06 08:55
```
$ lxc profile show default
config: {}
description: Default LXD profile
devices:
  eth0:
    nictype: bridged
    parent: lxdbr0
    type: nic
  root:
    path: /
    pool: default
    type: disk
name: default
used_by:
- /1.0/containers/juju-054c48-0
- /1.0/containers/juju-25cb4e-0
- /1.0/containers/juju-25cb4e-1
```
As a reference, current situation with juju-status
```
juju status
Model                        Controller                Cloud/Region         Version  SLA
conjure-kubernetes-core-0f3  conjure-up-localhost-ab6  localhost/localhost  2.3.8    unsupported

App                Version  Status   Scale  Charm              Store       Rev  OS      Notes
easyrsa            3.0.1    active       1  easyrsa            jujucharms   44  ubuntu  
etcd               n/a      error        1  etcd               jujucharms   87  ubuntu  
flannel            0.9.1    waiting      2  flannel            jujucharms   59  ubuntu  
kubernetes-master  1.10.3   error        1  kubernetes-master  jujucharms  113  ubuntu  exposed
kubernetes-worker  1.10.3   error        1  kubernetes-worker  jujucharms  128  ubuntu  exposed

Unit                  Workload  Agent  Machine  Public address  Ports           Message
easyrsa/0*            active    idle   0/lxd/0  10.0.171.247                    Certificate Authority connected.
etcd/0*               error     idle   0        10.134.7.137    2379/tcp        hook failed: "config-changed"
kubernetes-master/0*  error     idle   0        10.134.7.137    6443/tcp        hook failed: "config-changed"
  flannel/0*          waiting   idle            10.134.7.137                    Waiting for Flannel
kubernetes-worker/0*  error     idle   1        10.134.7.113    80/tcp,443/tcp  hook failed: "config-changed"
  flannel/1           waiting   idle            10.134.7.113                    Waiting for Flannel

Machine  State    DNS           Inst id              Series  AZ  Message
0        started  10.134.7.137  juju-25cb4e-0        xenial      Running
0/lxd/0  started  10.0.171.247  juju-25cb4e-0-lxd-0  xenial      Container started
1        started  10.134.7.113  juju-25cb4e-1        xenial      Running
```
My current research is about these messages 
```
$ dmesg|tail
[59328.549787] audit: type=1400 audit(1528274661.619:2485): apparmor="DENIED" operation="change_onexec" info="label not found" error=-2 profile="/usr/lib/snapd/snap-confine" name="snap.kubelet.kubelet" pid=30059 comm="snap-confine"
[59395.004942] audit: type=1400 audit(1528274728.075:2486): apparmor="DENIED" operation="change_onexec" info="label not found" error=-2 profile="/usr/lib/snapd/snap-confine" name="snap-update-ns.etcd" pid=32053 comm="snap-confine"
[59395.336961] audit: type=1400 audit(1528274728.407:2487): apparmor="DENIED" operation="change_onexec" info="label not found" error=-2 profile="/usr/lib/snapd/snap-confine" name="snap-update-ns.etcd" pid=32133 comm="snap-confine"
[59395.672921] audit: type=1400 audit(1528274728.743:2488): apparmor="DENIED" operation="change_onexec" info="label not found" error=-2 profile="/usr/lib/snapd/snap-confine" name="snap-update-ns.etcd" pid=32212 comm="snap-confine"
[59397.804850] audit: type=1400 audit(1528274730.875:2489): apparmor="DENIED" operation="change_onexec" info="label not found" error=-2 profile="/usr/lib/snapd/snap-confine" name="snap-update-ns.etcd" pid=33004 comm="snap-confine"
[59399.904920] audit: type=1400 audit(1528274732.975:2490): apparmor="DENIED" operation="change_onexec" info="label not found" error=-2 profile="/usr/lib/snapd/snap-confine" name="snap-update-ns.kube-apiserver" pid=33664 comm="snap-confine"
[59634.256046] audit: type=1400 audit(1528274967.323:2491): apparmor="DENIED" operation="change_onexec" info="label not found" error=-2 profile="/usr/lib/snapd/snap-confine" name="snap.kubelet.kubelet" pid=36496 comm="snap-confine"
[59701.496976] audit: type=1400 audit(1528275034.567:2492): apparmor="DENIED" operation="change_onexec" info="label not found" error=-2 profile="/usr/lib/snapd/snap-confine" name="snap-update-ns.etcd" pid=38223 comm="snap-confine"
[59703.856970] audit: type=1400 audit(1528275036.927:2493): apparmor="DENIED" operation="change_onexec" info="label not found" error=-2 profile="/usr/lib/snapd/snap-confine" name="snap-update-ns.kube-apiserver" pid=38992 comm="snap-confine"
[59939.847565] audit: type=1400 audit(1528275272.915:2494): apparmor="DENIED" operation="change_onexec" info="label not found" error=-2 profile="/usr/lib/snapd/snap-confine" name="snap.kubelet.kubelet" pid=2455 comm="snap-confine"
```

**Comment by gonfva** [comment] 2018-06-06 14:23
Something I've noticed is that aa-status reports a few differences. In particular there is no profile for snap.etcd.etcd after reboot. Attached files.

[aa-status-after-reboot.txt](https://github.com/conjure-up/conjure-up/files/2076633/aa-status-after-reboot.txt)
[aa-status-before-reboot.txt](https://github.com/conjure-up/conjure-up/files/2076634/aa-status-before-reboot.txt)

Also before reboot, when conjure-up is creating the cluster, there are multiple apparmor messages in the logs

```
[ 2346.314191] audit: type=1400 audit(1528293648.071:2703): apparmor="DENIED" operation="mkdir" profile="snap.kube-apiserver.daemon" name="/run/kubernetes/" pid=13076 comm="kube-apiserver" requested_mask="c" denied_mask="c" fsuid=0 ouid=0
[ 2347.082807] audit: type=1400 audit(1528293648.839:2704): apparmor="DENIED" operation="mkdir" profile="snap.kube-apiserver.daemon" name="/run/kubernetes/" pid=13639 comm="kube-apiserver" requested_mask="c" denied_mask="c" fsuid=0 ouid=0
[ 2348.156827] audit: type=1400 audit(1528293649.915:2705): apparmor="DENIED" operation="mkdir" profile="snap.kube-apiserver.daemon" name="/run/kubernetes/" pid=14371 comm="kube-apiserver" requested_mask="c" denied_mask="c" fsuid=0 ouid=0
[ 2348.893682] audit: type=1400 audit(1528293650.651:2706): apparmor="DENIED" operation="mkdir" profile="snap.kube-apiserver.daemon" name="/run/kubernetes/" pid=15156 comm="kube-apiserver" requested_mask="c" denied_mask="c" fsuid=0 ouid=0
[ 2349.992876] audit: type=1400 audit(1528293651.751:2707): apparmor="DENIED" operation="mkdir" profile="snap.kube-apiserver.daemon" name="/run/kubernetes/" pid=15708 comm="kube-apiserver" requested_mask="c" denied_mask="c" fsuid=0 ouid=0
[ 2363.343031] audit: type=1400 audit(1528293665.099:2708): apparmor="DENIED" operation="create" profile="snap.kube-apiserver.hook.configure" pid=26207 comm="snapctl" family="inet" sock_type="stream" protocol=6 requested_mask="create" denied_mask="create"
[ 2363.343040] audit: type=1400 audit(1528293665.099:2709): apparmor="DENIED" operation="create" profile="snap.kube-apiserver.hook.configure" pid=26207 comm="snapctl" family="inet6" sock_type="stream" protocol=6 requested_mask="create" denied_mask="create"
[ 2363.343045] audit: type=1400 audit(1528293665.099:2710): apparmor="DENIED" operation="create" profile="snap.kube-apiserver.hook.configure" pid=26207 comm="snapctl" family="inet6" sock_type="stream" protocol=6 requested_mask="create" denied_mask="create"
[ 2363.372054] audit: type=1400 audit(1528293665.127:2711): apparmor="DENIED" operation="create" profile="snap.kube-apiserver.hook.configure" pid=26221 comm="snapctl" family="inet" sock_type="stream" protocol=6 requested_mask="create" denied_mask="create"
[ 2363.372059] audit: type=1400 audit(1528293665.127:2712): apparmor="DENIED" operation="create" profile="snap.kube-apiserver.hook.configure" pid=26221 comm="snapctl" family="inet6" sock_type="stream" protocol=6 requested_mask="create" denied_mask="create"
[ 2363.372073] audit: type=1400 audit(1528293665.127:2713): apparmor="DENIED" operation="create" profile="snap.kube-apiserver.hook.configure" pid=26221 comm="snapctl" family="inet6" sock_type="stream" protocol=6 requested_mask="create" denied_mask="create"
[ 2363.394731] audit: type=1400 audit(1528293665.151:2714): apparmor="DENIED" operation="create" profile="snap.kube-apiserver.hook.configure" pid=26230 comm="snapctl" family="inet" sock_type="stream" protocol=6 requested_mask="create" denied_mask="create"
[ 2363.394737] audit: type=1400 audit(1528293665.151:2715): apparmor="DENIED" operation="create" profile="snap.kube-apiserver.hook.configure" pid=26230 comm="snapctl" family="inet6" sock_type="stream" protocol=6 requested_mask="create" denied_mask="create"
[ 2363.394741] audit: type=1400 audit(1528293665.151:2716): apparmor="DENIED" operation="create" profile="snap.kube-apiserver.hook.configure" pid=26230 comm="snapctl" family="inet6" sock_type="stream" protocol=6 requested_mask="create" denied_mask="create"
[ 2363.421079] audit: type=1400 audit(1528293665.179:2717): apparmor="DENIED" operation="create" profile="snap.kube-apiserver.hook.configure" pid=26244 comm="snapctl" family="inet" sock_type="stream" protocol=6 requested_mask="create" denied_mask="create"
[...]
```

**Comment by battlemidget** [comment] 2018-06-06 16:32
@Cynerva any idea on this?

@gonfva can you grab cdk-field-agent output and attach to this issue as well, https://github.com/juju-solutions/cdk-field-agent

Should give us better idea of what's going on

**Comment by gonfva** [comment] 2018-06-06 16:39
Sure. Attached. Thanks again.

[results-2018-06-06-17-34-08.tar.gz](https://github.com/conjure-up/conjure-up/files/2077238/results-2018-06-06-17-34-08.tar.gz)

This other piece appears in the logs when doing conjure-up (still gut-feeling apparmor related, but feel free to disregard it)

```
Jun  6 17:09:01 megacity01 conjure-up/kubernetes-core: [DEBUG] (conjure-up-localhost-a45:conjure-kubernetes-core-725) Running pre-deploy for kubernetes-core
Jun  6 17:09:01 megacity01 kernel: [ 7221.758373] audit: type=1400 audit(1528301341.281:3725): apparmor="DENIED" operation="file_inherit" profile="/snap/core/4734/usr/lib/snapd/snap-confine" pid=40526 comm="snap-confine" family="unix" sock_type="stream" protocol=0 requested_mask="send receive" denied_mask="send receive" addr=none peer_addr=none
Jun  6 17:09:01 megacity01 kernel: [ 7221.761357] audit: type=1400 audit(1528301341.285:3726): apparmor="DENIED" operation="file_inherit" profile="snap.lxd.lxc" name="/apparmor/.null" pid=40526 comm="snap-exec" requested_mask="wr" denied_mask="wr" fsuid=1000 ouid=0
Jun  6 17:09:01 megacity01 Setting PreDeployComplete at conjureup/controllers/deploy/common.py:13
Jun  6 17:09:01 megacity01 Deploying Applications.
Jun  6 17:09:03 megacity01 kernel: [ 7223.864022] audit: type=1400 audit(1528301343.389:3727): apparmor="DENIED" operation="file_mmap" namespace="root//lxd-juju-31646d-0_<var-snap-lxd-common-lxd>" profile="/usr/lib/lxd/lxd-bridge-proxy" name="/usr/lib/lxd/lxd-bridge-proxy" pid=40700 comm="lxd-bridge-prox" requested_mask="m" denied_mask="m" fsuid=1000000 ouid=1000000
```

**Comment by jzoldak** [comment] 2018-06-06 16:56
I'm having the same exact symptoms/issue on xenial (Ubuntu 16.04.4 LTS). Conjures up, doesn't survive a reboot. Same `dmesg` apparmor="DENIED" messages.

FWIW the stacktrace from `juju debug-log` looks like for each one it might be (? unsure) kicking off a subprocess that is running sanity check command (giving back the version) to determine that the service is installed in the container. 
```
unit-etcd-0: 15:59:08 DEBUG unit.etcd/0.config-changed Traceback (most recent call last):
unit-etcd-0: 15:59:08 DEBUG unit.etcd/0.config-changed   File "/var/lib/juju/agents/unit-etcd-0/charm/hooks/config-changed", line 19, in <module>
unit-etcd-0: 15:59:08 DEBUG unit.etcd/0.config-changed     main()
unit-etcd-0: 15:59:08 DEBUG unit.etcd/0.config-changed   File "/var/lib/juju/agents/unit-etcd-0/.venv/lib/python3.5/site-packages/charms/reactive/__init__.py", line 72, in main
unit-etcd-0: 15:59:08 DEBUG unit.etcd/0.config-changed     bus.dispatch(restricted=restricted_mode)
unit-etcd-0: 15:59:08 DEBUG unit.etcd/0.config-changed   File "/var/lib/juju/agents/unit-etcd-0/.venv/lib/python3.5/site-packages/charms/reactive/bus.py", line 382, in dispatch
unit-etcd-0: 15:59:08 DEBUG unit.etcd/0.config-changed     _invoke(other_handlers)
unit-etcd-0: 15:59:08 DEBUG unit.etcd/0.config-changed   File "/var/lib/juju/agents/unit-etcd-0/.venv/lib/python3.5/site-packages/charms/reactive/bus.py", line 358, in _invoke
unit-etcd-0: 15:59:08 DEBUG unit.etcd/0.config-changed     handler.invoke()
unit-etcd-0: 15:59:08 DEBUG unit.etcd/0.config-changed   File "/var/lib/juju/agents/unit-etcd-0/.venv/lib/python3.5/site-packages/charms/reactive/bus.py", line 180, in invoke
unit-etcd-0: 15:59:08 DEBUG unit.etcd/0.config-changed     self._action(*args)
unit-etcd-0: 15:59:08 DEBUG unit.etcd/0.config-changed   File "/var/lib/juju/agents/unit-etcd-0/charm/reactive/etcd.py", line 236, in send_single_connection_details
unit-etcd-0: 15:59:08 DEBUG unit.etcd/0.config-changed     db.set_connection_string(connection_string, version=etcdctl.version())
unit-etcd-0: 15:59:08 DEBUG unit.etcd/0.config-changed   File "lib/etcdctl.py", line 163, in version
unit-etcd-0: 15:59:08 DEBUG unit.etcd/0.config-changed     out = self.run('{} --version'.format(etcdctl_command()))
unit-etcd-0: 15:59:08 DEBUG unit.etcd/0.config-changed   File "lib/etcdctl.py", line 158, in run
unit-etcd-0: 15:59:08 DEBUG unit.etcd/0.config-changed     return check_output(split(command)).decode('ascii')
unit-etcd-0: 15:59:08 DEBUG unit.etcd/0.config-changed   File "/usr/lib/python3.5/subprocess.py", line 626, in check_output
unit-etcd-0: 15:59:08 DEBUG unit.etcd/0.config-changed     **kwargs).stdout
unit-etcd-0: 15:59:08 DEBUG unit.etcd/0.config-changed   File "/usr/lib/python3.5/subprocess.py", line 708, in run
unit-etcd-0: 15:59:08 DEBUG unit.etcd/0.config-changed     output=stdout, stderr=stderr)
unit-etcd-0: 15:59:08 DEBUG unit.etcd/0.config-changed subprocess.CalledProcessError: Command '['/snap/bin/etcd.etcdctl', '--version']' returned non-zero exit status 1
unit-etcd-0: 15:59:08 ERROR juju.worker.uniter.operation hook "config-changed" failed: exit status 1
unit-etcd-0: 15:59:08 INFO juju.worker.uniter awaiting error resolution for "config-changed" hook
```

**Comment by battlemidget** [comment] 2018-06-06 16:58
@jzoldak can you attach the cdk-field-agent output as well? I'm talking with the k8s guys right now

**Comment by jzoldak** [comment] 2018-06-06 17:04
@battlemidget sure thing. redeploying now, as I destroyed my earlier setup...

**Comment by battlemidget** [comment] 2018-06-06 17:04
> @battlemidget sure thing. redeploying now, as I destroyed my earlier setup...

Thanks, make sure to do the reboot first

**Comment by jzoldak** [comment] 2018-06-06 17:42
Steps taken:
- reboot
- conjure-up, wait for everything to settle down
- cdk-field-agent output before reboot: [before-results-2018-06-06-13-30-01.tar.gz](https://github.com/conjure-up/conjure-up/files/2077471/before-results-2018-06-06-13-30-01.tar.gz)
- reboot
- wait for juju status to show everything settled down
- cdk-field-agent output after reboot: 
[after-results-2018-06-06-13-36-26.tar.gz](https://github.com/conjure-up/conjure-up/files/2077479/after-results-2018-06-06-13-36-26.tar.gz)

**Comment by aug70** [comment] 2018-06-06 18:28
Running into same issue... Using **dir** driver (see below) because _zfs_ driver didn't work (related to #1430). Besides that, completely health cluster, everything working fine and when I reboot host, cluster is all messed up.

```
lxc storage list

+------------+-------------+--------+------------------------------------------------+---------+
|    NAME    | DESCRIPTION | DRIVER |                     SOURCE                     | USED BY |
+------------+-------------+--------+------------------------------------------------+---------+
| default    |             | dir    | /var/snap/lxd/common/lxd/storage-pools/default | 12      |
+------------+-------------+--------+------------------------------------------------+---------+
| juju-btrfs |             | btrfs  | /var/snap/lxd/common/lxd/disks/juju-btrfs.img  | 0       |
+------------+-------------+--------+------------------------------------------------+---------+
| juju-zfs   |             | zfs    | /var/snap/lxd/common/lxd/disks/juju-zfs.img    | 0       |
+------------+-------------+--------+------------------------------------------------+---------+
```

Ubuntu 18.04, /snap/bin/lxc, /snap/bin/lxd, lxd version 3.1, lxc version 3.1 server-3.1 client

After restart

```
lxc list
+---------------+---------+----------------------+------+------------+-----------+
|     NAME      |  STATE  |         IPV4         | IPV6 |    TYPE    | SNAPSHOTS |
+---------------+---------+----------------------+------+------------+-----------+
| juju-372386-0 | RUNNING | 10.197.70.6 (eth0)   |      | PERSISTENT | 0         |
+---------------+---------+----------------------+------+------------+-----------+
| juju-372386-1 | RUNNING | 10.197.70.125 (eth0) |      | PERSISTENT | 0         |
+---------------+---------+----------------------+------+------------+-----------+
| juju-372386-2 | RUNNING |                      |      | PERSISTENT | 0         |
+---------------+---------+----------------------+------+------------+-----------+
| juju-372386-3 | RUNNING |                      |      | PERSISTENT | 0         |
+---------------+---------+----------------------+------+------------+-----------+
| juju-372386-4 | RUNNING |                      |      | PERSISTENT | 0         |
+---------------+---------+----------------------+------+------------+-----------+
| juju-372386-5 | RUNNING |                      |      | PERSISTENT | 0         |
+---------------+---------+----------------------+------+------------+-----------+
| juju-372386-6 | RUNNING |                      |      | PERSISTENT | 0         |
+---------------+---------+----------------------+------+------------+-----------+
| juju-372386-7 | RUNNING | 10.197.70.193 (eth0) |      | PERSISTENT | 0         |
+---------------+---------+----------------------+------+------------+-----------+
| juju-372386-8 | RUNNING | 10.197.70.144 (eth0) |      | PERSISTENT | 0         |
+---------------+---------+----------------------+------+------------+-----------+
| juju-eeb458-0 | RUNNING | 10.197.70.147 (eth0) |      | PERSISTENT | 0         |
+---------------+---------+----------------------+------+------------+-----------+
```

```
 juju status
Model                         Controller                Cloud/Region         Version  SLA
conjure-canonical-kubern-e9f  conjure-up-localhost-e51  localhost/localhost  2.3.7    unsupported

App                    Version  Status   Scale  Charm                  Store       Rev  OS      Notes
easyrsa                3.0.1    active       1  easyrsa                jujucharms   44  ubuntu
etcd                   3.2.9    waiting    1/3  etcd                   jujucharms   87  ubuntu
flannel                0.9.1    active     2/4  flannel                jujucharms   59  ubuntu
kubeapi-load-balancer  1.10.3   active     0/1  kubeapi-load-balancer  jujucharms   62  ubuntu  exposed
kubernetes-master      1.10.3   active     0/1  kubernetes-master      jujucharms  113  ubuntu
kubernetes-worker      1.10.3   active     2/3  kubernetes-worker      jujucharms  128  ubuntu  exposed

Unit                      Workload  Agent  Machine  Public address  Ports           Message
easyrsa/0*                active    idle   0        10.197.70.6                     Certificate Authority connected.
etcd/0                    waiting   idle   1        10.197.70.125   2379/tcp        Waiting to retry etcd registration
etcd/1                    unknown   lost   2        10.197.70.222   2379/tcp        agent lost, see 'juju show-status-log etcd/1'
etcd/2*                   unknown   lost   3        10.197.70.76    2379/tcp        agent lost, see 'juju show-status-log etcd/2'
kubeapi-load-balancer/0*  unknown   lost   4        10.197.70.45    443/tcp         agent lost, see 'juju show-status-log kubeapi-load-balancer/0'
kubernetes-master/0*      unknown   lost   5        10.197.70.130   6443/tcp        agent lost, see 'juju show-status-log kubernetes-master/0'
  flannel/0               unknown   lost            10.197.70.130                   agent lost, see 'juju show-status-log flannel/0'
kubernetes-worker/0       unknown   lost   6        10.197.70.62    80/tcp,443/tcp  agent lost, see 'juju show-status-log kubernetes-worker/0'
  flannel/2               unknown   lost            10.197.70.62                    agent lost, see 'juju show-status-log flannel/2'
kubernetes-worker/1*      active    idle   7        10.197.70.193   80/tcp,443/tcp  Kubernetes worker running.
  flannel/1*              active    idle            10.197.70.193                   Flannel subnet 10.1.37.1/24
kubernetes-worker/2       active    idle   8        10.197.70.144   80/tcp,443/tcp  Kubernetes worker running.
  flannel/3               active    idle            10.197.70.144                   Flannel subnet 10.1.35.1/24

Machine  State    DNS            Inst id        Series  AZ  Message
0        started  10.197.70.6    juju-372386-0  xenial      Running
1        started  10.197.70.125  juju-372386-1  xenial      Running
2        down     10.197.70.222  juju-372386-2  xenial      Running
3        down     10.197.70.76   juju-372386-3  xenial      Running
4        down     10.197.70.45   juju-372386-4  xenial      Running
5        down     10.197.70.130  juju-372386-5  xenial      Running
6        down     10.197.70.62   juju-372386-6  xenial      Running
7        started  10.197.70.193  juju-372386-7  xenial      Running
8        started  10.197.70.144  juju-372386-8  xenial      Running

Relation provider                    Requirer                             Interface         Type         Message
easyrsa:client                       etcd:certificates                    tls-certificates  regular
easyrsa:client                       kubeapi-load-balancer:certificates   tls-certificates  regular
easyrsa:client                       kubernetes-master:certificates       tls-certificates  regular
easyrsa:client                       kubernetes-worker:certificates       tls-certificates  regular
etcd:cluster                         etcd:cluster                         etcd              peer
etcd:db                              flannel:etcd                         etcd              regular
etcd:db                              kubernetes-master:etcd               etcd              regular
kubeapi-load-balancer:loadbalancer   kubernetes-master:loadbalancer       public-address    regular
kubeapi-load-balancer:website        kubernetes-worker:kube-api-endpoint  http              regular
kubernetes-master:cni                flannel:cni                          kubernetes-cni    subordinate
kubernetes-master:kube-api-endpoint  kubeapi-load-balancer:apiserver      http              regular
kubernetes-master:kube-control       kubernetes-worker:kube-control       kube-control      regular
kubernetes-worker:cni                flannel:cni                          kubernetes-cni    subordinate
```

**Comment by battlemidget** [comment] 2018-06-06 23:52
@Cynerva @hyperbolic2346 @kwmonroe really need to add more reboot tests

**Comment by aug70** [comment] 2018-06-07 03:04
May be an easy fix?? I saw other juju charms run into **hook failed: "leader-settings-changed"** problems in the past and this seems to be mainly caused by etcd not handling this hook failure. When etcd fails, rest of the stuff goes down like dominoes...

**Comment by battlemidget** [comment] 2018-06-07 16:36
Thanks everyone, we've identified the issue and are currently working on a solution.

What's happening is that after a reboot some of the apparmor profiles aren't being re-applied and causing the errors seen here.

A quick workaround to follow

**Comment by Cynerva** [comment] 2018-06-07 16:47
I'm able to reproduce the issue where hooks fail with apparmor denials after rebooting the host machine.

It looks like snapd apparmor profiles aren't being reapplied after rebooting the host. I'm still looking into why this is happening, but for now, it looks like you can work around this by manually re-applying the snapd apparmor profiles:

```
juju run --all 'sudo apparmor_parser /var/lib/snapd/apparmor/profiles/*'
```

**Comment by Cynerva** [comment] 2018-06-25 15:32
The fix/workaround has been merged: https://github.com/juju-solutions/layer-cdk-service-kicker/pull/2

It is currently available in edge/beta/candidate charm channels, but has not been released to stable yet.

**Comment by gonfva-bcl** [comment] 2018-06-29 13:24
I removed my existing cluster, redeployed with edge and I can confirm it works after restart.

Thanks everybody.

**Comment by Cynerva** [comment] 2018-06-29 17:47
Fix has been released to stable, closing the issue. Thanks all.

**Closed by Cynerva** 2018-06-29 17:47 UTC
