### ISSUE TITLE
Conjure-up bootstrapping not working on 16.04

### ISSUE THREAD

**Issue by TJKoury** [conjure-up/conjure-up#535] opened 2016-12-22 15:56 UTC
Running against MAAS 2.0, environment correctly filled out in juju.   Running juju bootstrap seems to work, but conjure-up throws an error about a missing controller:

```
  Error: No controllers registered.

Please either create a new controller using "juju bootstrap" or connect to
another controller that you have been given access to using "juju register".

```

**Comment by battlemidget** [comment] 2016-12-22 16:38
What version of conjure-up, maas, and juju do you have installed?

**Comment by TJKoury** [comment] 2016-12-22 17:37
MAAS Version 2.1.2+bzr5555-0ubuntu1 (16.04.1)
conjure-up 0.1.2
2.0.2-xenial-amd64

**Comment by battlemidget** [comment] 2016-12-22 20:25
Make sure you're following the instructions from http://conjure-up.io as the most recent version of conjure-up is 2.0.2

**Comment by TJKoury** [comment] 2016-12-22 20:45
I've followed those steps, I'm now at:

MAAS Version 2.1.2+bzr5555-0ubuntu1 (16.04.1)
conjure-up 2.0.2
2.0.2-xenial-amd64

**Comment by battlemidget** [comment] 2016-12-22 20:47
Are your maas nodes going from ready to deployed?

**Comment by TJKoury** [comment] 2016-12-22 20:53
No, three are at pending and one is down.

**Comment by battlemidget** [comment] 2016-12-22 20:57
Yea so looks like you haven't configured your MAAS properly, for help with that I would join #maas on irc.freenode.net or head over to askubuntu.com

**Comment by TJKoury** [comment] 2016-12-22 20:59
What's interesting about that is MAAS through the GUI and API reports all three deployed.  Juju doesn't seem to share that opinion, though, as watching the status leads to the state flickering from started / down /pending.

**Comment by battlemidget** [comment] 2016-12-22 21:08
Can you run a juju bootstrap outside of conjure-up? Append the `--debug` flag to see where it may be failing at

**Comment by TJKoury** [comment] 2016-12-22 21:16
Yes, I can run it, works fine.  If I run conjure-up with no controllers registered, I get:

`Unable to list models: error: No controllers registered.`

**Comment by battlemidget** [comment] 2016-12-22 21:20
Yep we call juju bootstrap from conjure-up, can you `pastebinit ~/.cache/conjure-up/conjure-up.log` and also the output of `juju status --format yaml|pastebinit`  from a failed conjure-up attempt.

**Comment by battlemidget** [comment] 2016-12-22 21:20
Also, do you have any firewall restrictions?

**Comment by TJKoury** [comment] 2016-12-22 21:22
http://paste.ubuntu.com/23670243/

No firewall restrictions, DNS & DHCP configured on MAAS controller, all machines plugged into dedicated switch with no other traffic.

**Comment by battlemidget** [comment] 2016-12-22 21:23
Is this a setup I can login to and checkout?

**Comment by TJKoury** [comment] 2016-12-22 21:26
Unfortunately no, at the moment.  This is part of a internal test setup. 

BTW, looking at the log, it seems like conjure-up is unable to resolve the DNS name 'maas.controller', which is the internal name for the ....  maas controller.  It also seems to try the IP, which is correct, but still fails.  How is the 'region' configured that it's trying to look up these identifiers?  It seems like it's an empty array.

**Comment by battlemidget** [comment] 2016-12-22 21:28
Do me a favor, if possible tear down any existing juju environments you may have running. Then `rm -rf ~/.local/share/juju` and retry `conjure-up`.

**Comment by battlemidget** [comment] 2016-12-22 21:30
conjure-up just exec's out a typical `juju bootstrap ..` command. Everything else is handled through the Juju API controller. I didnt see the actual juju bootstrap command though in the log file

**Comment by TJKoury** [comment] 2016-12-22 21:31
doing ^^^^.  BTW, is there any way to run 'juju status' while conjure-up is bootstrapping?  The result of running it gives me `ERROR no API addresses`

**Comment by battlemidget** [comment] 2016-12-22 21:32
Unfortunately no. The only way to get better debug output for the bootstrap portion is to bootstrap with `--debug`

**Comment by TJKoury** [comment] 2016-12-22 21:32
so `conjure-up --debug`?

**Comment by TJKoury** [comment] 2016-12-22 21:34
Appreciate the response time, btw.

**Comment by battlemidget** [comment] 2016-12-22 21:35
If you're comfortable enough you could append a `--debug` switch to the bootstrap code

https://github.com/conjure-up/conjure-up/blob/master/conjureup/juju.py#L167

Something like:

```
cmd += "--debug --bootstrap-series={} ".format(series)
```

That'll log more info into ~/.cache/conjure-up/SPELL/*.{err,out}

**Comment by battlemidget** [comment] 2016-12-22 21:36
also filed https://github.com/conjure-up/conjure-up/issues/536 not sure why we don't have that

**Comment by TJKoury** [comment] 2016-12-22 21:36
Makes sense.  If I add a pull request will Canonical cut me a check? :)

**Comment by battlemidget** [comment] 2016-12-22 21:37
hah, I'll create an AUTHORS file and put you at the top :D

**Comment by battlemidget** [comment] 2016-12-22 21:38
If you give me a few ill push some code out to our daily-git ppa and you can try that

**Comment by battlemidget** [comment] 2016-12-22 21:39
Also are you running MAAS from proposed? I only have MAAS 2.1.1+bzr5544 running in my lab

**Comment by TJKoury** [comment] 2016-12-22 21:40
Hmmm, no.  From a fresh 16.04 install: 

 ` 19  sudo add-apt-repository ppa:maas/stable
   20  sudo apt-get update
   21  sudo apt-get install maas
`

**Comment by battlemidget** [comment] 2016-12-22 21:41
Ah ok from their ppa, lemme upgrade my lab and see if i can reproduce as well

**Comment by battlemidget** [comment] 2016-12-22 21:46
can you join #ubuntu-solutions on irc.freenode.net? would be easier to debug, my nick is `stokachu` on there

**Comment by TJKoury** [comment] 2016-12-22 21:46
kk

**Comment by battlemidget** [comment] 2016-12-23 03:10
I poked at this a little more and there seems to be some issues with Juju and the MAAS 2.1.2 release. I haven't nailed down anything specific but since upgrading my lab to that MAAS release I've been unable to bootstrap a system (though deploying via the MAAS UI works).

I'll keep digging

**Comment by TJKoury** [comment] 2016-12-23 14:20
I've installed everything using the versions we discussed, and it seems like everything is working (using manual `juju bootstrap`).

One nuance is that although the Ubuntu documentation for Autopilot says you need 5 machines with dual NIC, you actually need 6, as Juju refuses to install anything on the bootstrap machine, and will not let you co-locate it with the maas controller.  Once I manually put all the Openstack services on the three remaining machines, everything runs ok (still throwing an error about neutron-openvswitch-agent service not running).  Also, Openstack dashboard just shows an empty directory with an `html` folder.

**Comment by battlemidget** [comment] 2016-12-23 15:35
So autopilot isn't ready for juju 2.0 quite yet, you're probably using the OpenStack for MAAS.  The colocation issue will be addressed in our next big conjure-up release as that will support placement and machine pinning. Please close this if the issue is addressed.  I'm still investigating the latest maas stable release.

**Comment by battlemidget** [comment] 2017-01-24 13:51
Were you able to make any progress on this?

**Comment by TJKoury** [comment] 2017-01-24 13:54
Honestly I gave up, just using lxd plus my own scripts, seems to be easier to manage than juju.  The REST API for lxd is simple to use.

**Comment by battlemidget** [comment] 2017-01-24 14:03
Sorry to hear that, we do have the openstack with novalxd option which puts everything in lxd containers for you but that is just for a single machine deployment.

Please let us know if you do decide to try again so we can dig into your setup more.

**Closed by battlemidget** 2017-01-24 14:03 UTC
Labels: bug, maas 2.0

**Comment by TJKoury** [comment] 2017-01-24 14:21
Ok, and thank you for taking the time to walk through the issues with me.
