### ISSUE TITLE
conjure-up localhost unable to locate liblxc.so.1

### ISSUE THREAD

**Issue by drpaneas** [conjure-up/conjure-up#955] opened 2017-06-20 01:50 UTC
## Report

Thank you for trying **conjure-up**! Before reporting a bug please make sure you've gone through this checklist:

- [ ] Is this problem already documented at https://docs.ubuntu.com/conjure-up/en/troubleshoot#common-spell-problems
- [x] Is conjure-up running inside a virtual machine?
- [x] Is this problem reproducible with `sudo snap refresh conjure-up --edge`?

## Please provide the output of the following commands

Command: `which juju`
_Output_: `/snap/bin/juju`

Command: `which conjure-up`
_Output_: `/snap/bin/conjure-up`

Command: `which lxd`
_Output_: **No output**

Command: `juju version`
_Output_:  `2.3-alpha1-zesty-amd64`

Command: `conjure-up --version`
_Output_: `conjure-up 2.3-alpha1`

Command: `lxd --version`
_Output_: **No output**
```bash
The program 'lxd' is currently not installed. You can install it by typing:
sudo apt install lxd
```

Command: `lxc config show` 
_Output_: **No output**
```bash
The program 'lxc' is currently not installed. You can install it by typing: 
sudo apt install lxd-client
```

Command: `cat /etc/lsb-release`
_Output_:
```bash
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=17.04
DISTRIB_CODENAME=zesty
DISTRIB_DESCRIPTION="Ubuntu 17.04"
```

Please attach tarball of **~/.cache/conjure-up**:

Command: `cat ~/.cache/conjure-up/conjure-up.log`
_Output_: **No output**. Empty log file.

## Sosreport

Please attach a sosreport:

[sosreport-pgeorgiadis.1-20170620031326.zip](https://github.com/conjure-up/conjure-up/files/1086723/sosreport-pgeorgiadis.1-20170620031326.zip)

## What Spell was Selected?

None. I just ran `conjure up`

## What provider (aws, maas, localhost, etc)?

`localhost`

### MAAS Users
Which version of MAAS?

I am afraid I can't answer that. How can I find the version of MAAS?

## Commands ran

Please outline what commands were run to install and execute `conjure-up`:

```bash
drpaneas@ubuntu1704:/snap$ conjure-up
Traceback (most recent call last):
  File "/snap/conjure-up/460/bin/conjure-up", line 11, in <module>
    load_entry_point('conjure-up==2.3a1', 'console_scripts', 'conjure-up')()
  File "/snap/conjure-up/460/lib/python3.6/site-packages/conjureup/app.py", line 241, in main
    utils.lxd_version(),
  File "/snap/conjure-up/460/lib/python3.6/site-packages/conjureup/utils.py", line 205, in lxd_version
    raise Exception("Could not determine LXD version.")
Exception: Could not determine LXD version.
```
**Note**: Please read [my post](https://forum.snapcraft.io/t/conjure-up-2-3-alpha-could-not-determine-lxd-version/1054) at _snapcraft forums_ in order to find more information.

## Additional Information

Also take a look at a snipper from my `journalctl`
[journalctl.txt](https://github.com/conjure-up/conjure-up/files/1086741/journalctl.txt)

in which I've noticed this:

```bash
drpaneas@ubuntu1704:/snap/conjure-up/460/bin$ ./lxd
./lxd: error while loading shared libraries: liblxc.so.1: cannot open shared object file: No such file or directory
```
I assume that the missing library `liblxc.so.1` should have been installed via SNAPS, right? I did some digging and it seems that this _file_ is included into [liblxc1](https://packages.ubuntu.com/zesty/amd64/liblxc1/filelist) package.

I have also noticed that `sudo systemctl status snap.conjure-up.daemon.service` fails:

```bash
Jun 20 02:46:12 ubuntu1704 systemd[1]: snap.conjure-up.daemon.service: Service hold-off time over, scheduling restart.
Jun 20 02:46:12 ubuntu1704 systemd[1]: Stopped Service for snap application conjure-up.daemon.
Jun 20 02:46:12 ubuntu1704 systemd[1]: snap.conjure-up.daemon.service: Start request repeated too quickly.
Jun 20 02:46:12 ubuntu1704 systemd[1]: Failed to start Service for snap application conjure-up.daemon.
Jun 20 02:46:12 ubuntu1704 systemd[1]: snap.conjure-up.daemon.service: Unit entered failed state.
Jun 20 02:46:12 ubuntu1704 systemd[1]: snap.conjure-up.daemon.service: Failed with result 'exit-code'.
Jun 20 03:37:22 ubuntu1704 systemd[1]: Started Service for snap application conjure-up.daemon.
Jun 20 03:37:22 ubuntu1704 /usr/bin/snap[4755]: cmd.go:114: DEBUG: not restarting into "/snap/core/current/usr/bin/snap" ([VERSION=2.24 2
Jun 20 03:37:22 ubuntu1704 snap[4755]: No "lxd" group found, only root will be able to use LXD.
Jun 20 03:37:22 ubuntu1704 snap[4755]: /snap/conjure-up/460/bin/lxd: error while loading shared libraries: liblxc.so.1: cannot open share
```

Also, my `$PATH` is `/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin`

Please do let me know if you need any further feedback. I am pretty new to *conjure-up* so I am not familiar with common debugging techniques yet :/

**Comment by battlemidget** [comment] 2017-06-20 03:05
So you can only run lxd via `conjure-up.lxd --version` (i've updated the issue template to reflect that). Also, you can run `sudo snap alias conjure-up.lxd lxd` `sudo snap alias conjure-up.lxc lxc`. So can you provide output of `conjure-up.lxd --version`?

**Comment by drpaneas** [comment] 2017-06-20 07:53
I've created the _aliases_ as requested:
```bash
sudo snap alias conjure-up.lxc lxc
sudo snap alias conjure-up.lxd lxd
```

Command: `$ lxd --version`
_Output_:
```bash
/snap/conjure-up/460/bin/lxd: error while loading shared libraries: liblxc.so.1: cannot open shared object file: No such file or directory
```

Command: `$ lxc --version`
_Output_ : `2.14`

I've also run  `strace` in case it's helpful for you:

- [strace.lxd.normal_user.txt](https://github.com/conjure-up/conjure-up/files/1087378/strace.lxd.normal_user.txt)

- [strace.lxd.with_sudo.txt](https://github.com/conjure-up/conjure-up/files/1087379/strace.lxd.with_sudo.txt)

**Comment by battlemidget** [comment] 2017-06-20 14:03
Also can you paste the output of `ldconfig -v`, im not entirely sure why liblxc1 is not being found when it's clearly being built in our snap.

**Comment by drpaneas** [comment] 2017-06-20 19:08
Command: `sudo /sbin/ldconfig -v &> ldconfig.txt`
_Output_: 
[ldconfig.txt](https://github.com/conjure-up/conjure-up/files/1089264/ldconfig.txt)

Since you said that `liblxc1` is built in snap, I searched about it and I found `liblxc.so.1.2.0` instead. Have a look:

```bash
drpaneas@ubuntu1704:~$  sudo find /snap -type f -iname "liblxc*"

/snap/conjure-up/469/lib/liblxc.so.1.2.0
/snap/conjure-up/469/lib/liblxcfs.so
/snap/conjure-up/460/lib/liblxc.so.1.2.0
/snap/conjure-up/460/lib/liblxcfs.so
```

with those permissions:

```bash
drpaneas@ubuntu1704:~$ for pkg in `sudo find /snap -type f -iname "liblxc*"`; do ls -l $pkg; done

-rwxr-xr-x 1 root root 806424 Jun 20 06:11 /snap/conjure-up/469/lib/liblxc.so.1.2.0
-rwxr-xr-x 1 root root 137800 Jun 20 06:18 /snap/conjure-up/469/lib/liblxcfs.so
-rwxr-xr-x 1 root root 806424 Jun 19 21:17 /snap/conjure-up/460/lib/liblxc.so.1.2.0
-rwxr-xr-x 1 root root 137800 Jun 19 21:25 /snap/conjure-up/460/lib/liblxcfs.so
```

Now I am not sure what the _469_ and _460_ folders represent, but I went into those and I found this:

```bash
drpaneas@ubuntu1704:/snap/conjure-up/469/lib$ ls -l liblxc.so.1
lrwxrwxrwx 1 root root 15 Jun 20 06:11 liblxc.so.1 -> liblxc.so.1.2.0
```

```bash
$ for symlink in `sudo find /snap -type l -iname "liblxc*"`; do ls -l $symlink; done
lrwxrwxrwx 1 root root 15 Jun 20 06:11 /snap/conjure-up/469/lib/liblxc.so.1 -> liblxc.so.1.2.0
lrwxrwxrwx 1 root root 15 Jun 19 21:17 /snap/conjure-up/460/lib/liblxc.so.1 -> liblxc.so.1.2.0
```

That has been said, snap definitely comes with `liblxc` (as you said). The problem is that it cannot find it. and I think I found why:

If you look at the **strace** (the one with _sudo_) output I've uploaded previously, then you will find the list of all the directories that the system looked for to find `liblxc.so`:

```bash
drpaneas@ubuntu1704:~/logs$ grep liblxc strace.lxd.with_sudo.txt 
open("/lib/x86_64-linux-gnu/tls/x86_64/liblxc.so.1", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/lib/x86_64-linux-gnu/tls/liblxc.so.1", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/lib/x86_64-linux-gnu/x86_64/liblxc.so.1", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/lib/x86_64-linux-gnu/liblxc.so.1", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/usr/lib/x86_64-linux-gnu/tls/x86_64/liblxc.so.1", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/usr/lib/x86_64-linux-gnu/tls/liblxc.so.1", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/usr/lib/x86_64-linux-gnu/x86_64/liblxc.so.1", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/usr/lib/x86_64-linux-gnu/liblxc.so.1", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/lib/tls/x86_64/liblxc.so.1", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/lib/tls/liblxc.so.1", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/lib/x86_64/liblxc.so.1", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/lib/liblxc.so.1", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/usr/lib/tls/x86_64/liblxc.so.1", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/usr/lib/tls/liblxc.so.1", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/usr/lib/x86_64/liblxc.so.1", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/usr/lib/liblxc.so.1", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
writev(2, [{"/snap/conjure-up/460/bin/lxd", 28}, {": ", 2}, {"error while loading shared libra"..., 36}, {": ", 2}, {"liblxc.so.1", 11}, {": ", 2}, {"cannot open shared object file", 30}, {": ", 2}, {"No such file or directory", 25}, {"\n", 1}], 10/snap/conjure-up/460/bin/lxd: error while loading shared libraries: liblxc.so.1: cannot open shared object file: No such file or directory
```

As you can see **it doesn't** look into `/snap/` directory, but it looks only into under `/usr/lib/` and `/lib/x86_64-linux-gnu/` instead.

## Workaround

So, I've finally managed to make it work by just adding a symlink in one of the above aforementioned directories :

```bash
$ sudo ln -s /snap/conjure-up/469/lib/liblxc.so.1.2.0 /usr/lib/x86_64-linux-gnu/liblxc.so.1
conjure-up
# it works without a problem now
```

My guess is that a solution would be to include the `/snap/` directory in the list of the ones that the system searches into when the user issues the `conjure-up` command.

**Comment by battlemidget** [comment] 2017-06-20 19:31
Thanks for going through the debugging, turns out we never set the LD_LIBRARY_PATH when we started bundling LXD :|

I have  PR for it up and once reviewed and merged ill get a new build out for you to try

**Comment by drpaneas** [comment] 2017-06-20 20:23
@johnsca Have you actually **verified** that [PR#968](https://github.com/conjure-up/conjure-up/issues/968) solves this issue before closing it? I am still waiting for @battlemidget to provide me with a build so I can test it. But if you test it yourself and you verified it works, then it's also fine :)

**Comment by battlemidget** [comment] 2017-06-20 20:27
@drpaneas well the actual problem is you are the only one that has reported this issue. I'm pushing out a build now and we can reopen this issue if the problem persists

**Comment by drpaneas** [comment] 2017-06-20 20:30
How is this possible that I am the only one? I am using Virtualbox and a typical ubuntu 17.04 VM and 17.10 VM. This problem should be 100% reproducable :/ That's weird ... interesting ...

**Comment by battlemidget** [comment] 2017-06-20 21:09
You just need to run

```
sudo snap refresh conjure-up --edge
```

**Comment by drpaneas** [comment] 2017-06-20 21:40
Still the same error ... it's _not_ fixed:

```bash
drpaneas@ubuntu1704:~$ sudo snap refresh conjure-up --edge

conjure-up (edge) 2.3-alpha1-20170620.2006 from 'canonical' refreshed


drpaneas@ubuntu1704:~$ conjure-up
Traceback (most recent call last):
  File "/snap/conjure-up/477/bin/conjure-up", line 11, in <module>
    load_entry_point('conjure-up==2.3a1', 'console_scripts', 'conjure-up')()
  File "/snap/conjure-up/477/lib/python3.6/site-packages/conjureup/app.py", line 241, in main
    utils.lxd_version(),
  File "/snap/conjure-up/477/lib/python3.6/site-packages/conjureup/utils.py", line 205, in lxd_version
    raise Exception("Could not determine LXD version.")
Exception: Could not determine LXD version.
```

 :(

**How to reproduce it**:
1. Download Ubuntu 17.10 or 17.04 or 16.04 iso
2. Boot from it and either install it or use the 'Try' live function
3. Open Terminal and type: `sudo snap install conjure-up --classic --edge`
4. Run `conjure-up`

Let me know if you can reproduce it, otherwise I will send you the `qcow2` image itself.

**Comment by battlemidget** [comment] 2017-06-20 21:42
You're going to have to provide the qcow2 image because I can't reproduce this

**Comment by drpaneas** [comment] 2017-06-21 11:50
Ok, the `*.qcow2` image can be found [here](http://37.187.99.56/blog/reproducer.qcow2)
`username`: linux
`password`: linux

**Comment by tim-jones-001** [comment] 2017-06-21 14:44
I confirm that I have been trying all day to get this to work and am experiencing exactly the same error as drpaneas with clean installs of ubuntu 16.04 on a dell server:

$ `conjure-up`
Traceback (most recent call last):
  File "/snap/conjure-up/480/bin/conjure-up", line 11, in <module>
    load_entry_point('conjure-up==2.3a1', 'console_scripts', 'conjure-up')()
  File "/snap/conjure-up/480/lib/python3.6/site-packages/conjureup/app.py", line 241, in main
    utils.lxd_version(),
  File "/snap/conjure-up/480/lib/python3.6/site-packages/conjureup/utils.py", line 205, in lxd_version
    raise Exception("Could not determine LXD version.")
Exception: Could not determine LXD version.

(The above was after `sudo snap refresh conjure-up --edge`)

**Comment by battlemidget** [comment] 2017-06-21 14:46
Downloading the qcow image now to try and reproduce, thanks for the second confirm @tim-jones-001

**Comment by battlemidget** [comment] 2017-06-21 15:01
Thanks I can reproduce with this qcow image

**Comment by battlemidget** [comment] 2017-06-21 15:09
OK, so first a disclaimer

**This is only a workaround until I can figure out why the bundled lxd is not looking for the bundled liblxc lib**

To workaround:

```
sudo apt install liblxc1
```

Again this is just a workaround and something to do with how we are trying to load our bundled libraries inside the snap. But at least for now you can get it going to play with.

**Comment by tim-jones-001** [comment] 2017-06-21 16:05
Unfortunately having run `sudo apt install liblxc1` I am now getting a different error:
`Problem running lxd init: error: Unable to talk to LXD: Get Http://unix.socket/1.0: dial unix /var/snap/conjure-up/common/lxd/unix.socket: connect: permission denied`
conjure-up.log:
```
File "/snap/conjure-up/471/lib/python3.6/site-packages/conjureup/controllers/lxdsetup/common.py", line 70, in lxd_init
    cmd()
  File "/snap/conjure-up/471/lib/python3.6/site-packages/conjureup/controllers/lxdsetup/common.py", line 95, in set_lxd_init_auto
    "Problem running lxd init: {}".format(out.stderr.decode()))
Exception: Problem running lxd init: error: Unable to talk to LXD: Get http://unix.socket/1.0: dial unix /var/snap/conjure-up/common/lxd/unix.socket: connect: permission denied
Is this any easier to diagnose?

```

**Comment by battlemidget** [comment] 2017-06-21 18:27
Whats the output:

`sudo ls -l /var/snap/conjure-up/common/lxd/`

**Comment by battlemidget** [comment] 2017-06-21 18:58
@drpaneas @tim-jones-001 Got new builds going that should hopefully address this issue, once the builds have completed at https://launchpad.net/~adam-stokes/+snap/conjure-up ill let you know so you can try to reproduce. I'll also test on the VM you gave as well

**Comment by drpaneas** [comment] 2017-06-21 20:10
@battlemidget I've tested your [PR#972](https://github.com/conjure-up/conjure-up/issues/972) and it **fixes** the problem for me. Feel free to close this issue as _fixed_.

/LGTM

**Comment by battlemidget** [comment] 2017-06-21 21:15
Ty!

**Closed by battlemidget** 2017-06-21 21:15 UTC
Labels: bug, critical, test-track

**Comment by tim-jones-001** [comment] 2017-06-22 09:58
Working remotely and had to wait for physical server to be redeployed - apologies for delay.

Out put of sudo ls -l /var/snap/conjure-up/common/lxd/ is:

total 48
drwx------ 2 root root 4096 Jun 21 16:56 cache
drwx--x--x 2 root root 4096 Jun 21 16:56 containers
drwx--x--x 2 root root 4096 Jun 21 16:56 devices
drwxr-xr-x 2 root root   60 Jun 22 10:40 devlxd
drwx------ 2 root root 4096 Jun 21 16:56 disks
drwx------ 2 root root 4096 Jun 21 16:56 images
drwxr-xr-x 2 root root 4096 Jun 21 16:56 logs
lrwxrwxrwx 1 root root   24 Jun 21 16:56 lxd.db -> ../../current/lxd/lxd.db
drwx--x--x 2 root root 4096 Jun 21 16:56 networks
drwx------ 2 root root 4096 Jun 21 16:56 security
-rw-r--r-- 1 root root 1931 Jun 21 16:56 server.crt
-rw------- 1 root root 3243 Jun 21 16:56 server.key
drwx--x--x 2 root root   40 Jun 22 10:40 shmounts
drwx------ 2 root root 4096 Jun 21 16:56 snapshots
drwx--x--x 2 root root 4096 Jun 21 16:56 storage-pools
srw-rw---- 1 root root    0 Jun 22 10:40 unix.socket

Will the edge version of conjure-up now be your new build?

**Comment by tim-jones-001** [comment] 2017-06-22 10:10
I have just
* removed conjure-up and re-installed it
* run `sudo snap install conjure-up --classic --edge`
* run `conjure-up`
* chosen `localhost` as the cloud to deploy to

and get same error:

```
File "/snap/conjure-up/485/lib/python3.6/site-packages/conjureup/controllers/lxdsetup/common.py", line 70, in lxd_init
    cmd()
  File "/snap/conjure-up/485/lib/python3.6/site-packages/conjureup/controllers/lxdsetup/common.py", line 95, in set_lxd_init_auto
    "Problem running lxd init: {}".format(out.stderr.decode()))
Exception: Problem running lxd init: error: Unable to talk to LXD: Get http://unix.socket/1.0: dial unix /var/snap/conjure-up/common/lxd/unix.socket: connect: permission denied

2017-06-22 11:03:07,781 [DEBUG] conjure-up/openstack-novalxd - __init__.py:32 - Showing dialog for exception: Problem running lxd init: error: Unable to talk to LXD: Get http://unix.socket/1.0: dial unix /var/snap/conjure-up/common/lxd/unix.socket: connect: permission denied

```

@battlemidget Should I raise a separate issue?

**Comment by battlemidget** [comment] 2017-06-22 11:46
@tim-jones-001 Looks like the permissions are wrong on that socket file, try this:

```
sudo chown root:lxd /var/snap/conjure-up/common/lxd/unix.socket
```

**Comment by tim-jones-001** [comment] 2017-06-22 12:10
I've been through the same process of deleting everything and re-installing conjure-up, refreshing snap with --edge and running conjure-up, which now gives me the original error again:
```
Traceback (most recent call last):
  File "/snap/conjure-up/485/bin/conjure-up", line 11, in <module>
    load_entry_point('conjure-up==2.3a1', 'console_scripts', 'conjure-up')()
  File "/snap/conjure-up/485/lib/python3.6/site-packages/conjureup/app.py", line 241, in main
    utils.lxd_version(),
  File "/snap/conjure-up/485/lib/python3.6/site-packages/conjureup/utils.py", line 205, in lxd_version
    raise Exception("Could not determine LXD version.")
Exception: Could not determine LXD version.
```

**Comment by battlemidget** [comment] 2017-06-22 12:26
Is this a VM? Are you able to upload it somewhere so I can take a look?

**Comment by tim-jones-001** [comment] 2017-06-22 12:36
No sorry, it's a physical dell server (poweredge R719) which is 3 hours away drive from me now behind a vpn, so  whereas I could rebuild the OS from scratch (which I did several times) yesterday, today I cannot do so today.

Would be happy to have a web conf via hangouts or join.me and share my screen with you if you think that would help you narrow down what the issue is?

Really appreciate your taking the time to look into this for me.

**Comment by battlemidget** [comment] 2017-06-22 12:40
We can probably do that, first can you run:

```
conjure-up.lxd --version
```

I just want to make sure it's the same failed to load library problem

**Comment by tim-jones-001** [comment] 2017-06-22 12:42
Oddly I reverted to the user which I used initially to go through the process and I get the other error:
`Problem running lxd init: error: Unable to talk to LXD: Get Http://unix.socket/1.0: dial unix /var/snap/conjure-up/common/lxd/unix.socket: connect: permission denied
`
This was after running `sudo chown root:lxd /var/snap/conjure-up/common/lxd/unix.socket` as you suggested.

**Comment by battlemidget** [comment] 2017-06-22 12:45
Can you post the output of:

```
id
```

For the user you wish to run as?

**Comment by tim-jones-001** [comment] 2017-06-22 12:49
Sorry edits crossed

$ `conjure-up.lxd --version`
`2.14`
$ `id`
`uid=1000(rnd) gid=1000(rnd) groups=1000(rnd),4(adm),24(cdrom),27(sudo),30(dip),46(plugdev),113(lpadmin),128(sambashare),129(lxd)`

**Comment by battlemidget** [comment] 2017-06-22 12:50
Ok now that `conjure-up.lxd --version` works can you re-run `conjure-up`?

**Comment by tim-jones-001** [comment] 2017-06-22 13:08
This gives:
`Problem running lxc config: error: cannot listen on https socket: listen tcp [::]:12001: bind: address already in use`

**Comment by battlemidget** [comment] 2017-06-22 13:14
Ok, we're getting somewhere now, run:

```
conjure-up.lxc config set core.https_address [::]:12002
```

Then re-run `conjure-up`, I've got some fixes coming to address this problem as well

**Comment by tim-jones-001** [comment] 2017-06-22 13:18
Get same error:
`Problem running lxc config: error: cannot listen on https socket: listen tcp [::]:12001: bind: address already in use`

**Comment by battlemidget** [comment] 2017-06-22 13:19
Ok try,

```
conjure-up.lxc config unset core.https_address
conjure-up
```

**Comment by battlemidget** [comment] 2017-06-22 14:10
@tim-jones-001 any luck?

**Comment by tim-jones-001** [comment] 2017-06-22 15:19
(sorry was driving) 
still have same error:
`Problem running lxc config: error: cannot listen on https socket: listen tcp [::]:12001: bind: address already in use`

**Comment by battlemidget** [comment] 2017-06-22 15:20
Can you hop on https://rocket.ubuntu.com/channel/conjure-up? I'd like to track this error down as I've seen it come up a couple other times

**Comment by mickdelaney** [comment] 2017-07-09 11:10
getting this error, have tried it all, clean new 16.04 machine. 
its marked as closed ?

**Comment by battlemidget** [comment] 2017-07-09 11:18
Yes, it had been fixed as the port is auto generated based on what's free

**Comment by carpalex** [comment] 2017-07-17 16:39
Hi, I am still seeing the issue on a clean 16.04 image.
The image is the one from here:
https://cloud-images.ubuntu.com/xenial/20170716/xenial-server-cloudimg-amd64-disk1.img

Steps to reproduce:
ubuntu@conjure:~$ sudo snap install conjure-up --classic --edge
conjure-up (edge) 2.3-alpha1-20170713.0307 from 'canonical' installed
ubuntu@conjure:~$ conjure-up
Traceback (most recent call last):
  File "/snap/conjure-up/557/bin/conjure-up", line 11, in <module>
    load_entry_point('conjure-up==2.3a1', 'console_scripts', 'conjure-up')()
  File "/snap/conjure-up/557/lib/python3.6/site-packages/conjureup/app.py", line 257, in main
    utils.lxd_version(),
  File "/snap/conjure-up/557/lib/python3.6/site-packages/conjureup/utils.py", line 269, in lxd_version
    raise Exception("Could not determine LXD version.")
Exception: Could not determine LXD version.

**Comment by richardsith** [comment] 2017-07-17 16:48
same issue also for my lab.
![screen shot 2017-07-17 at 18 28 58](https://user-images.githubusercontent.com/9977215/28279380-95355d36-6b20-11e7-8eb2-e847026d2c8b.png)

**Comment by erihanse** [comment] 2017-07-17 17:14
Also, see #683

**Comment by battlemidget** [comment] 2017-07-17 17:37
huh this is an odd issue that i can't reproduce, still looking into this

**Comment by richardsith** [comment] 2017-07-17 17:39
I made the same lab three weeks ago and the deploy with conjure-up worked fine. Today re-build teh same lab I obtained that issue

**Comment by battlemidget** [comment] 2017-07-17 17:42
@richardsith thanks, can you take this over to the other bug as this bug was for liblxc library failing to load. post the output of `snap version` in the other bug as well please https://github.com/conjure-up/conjure-up/issues/683

**Comment by richardsith** [comment] 2017-07-17 17:43
@battlemidget  I've done it!
