### ISSUE TITLE
misleading error when ipv6 is enabled in lxd

### ISSUE THREAD

**Issue by sergiusens** [conjure-up/conjure-up#570] opened 2017-01-13 07:15 UTC
The error says that my accounts.yaml is missing but in reality
```
sergiusens@verified-martin:~$ juju bootstrap localhost
ERROR creating LXD client: /etc/default/lxd-bridge has IPv6 enabled.
Juju doesn't currently support IPv6.

IPv6 can be disabled by running:

       sudo dpkg-reconfigure -p medium lxd

and then bootstrap again.
```

**Comment by mikemccracken** [comment] 2017-01-13 07:42
thanks for filing!
this is a dupe of #495, so I'll close it here.

**Closed by mikemccracken** 2017-01-13 07:42 UTC
