### ISSUE TITLE
Flannel hook failed: "install"

### ISSUE THREAD

**Issue by JerryBeassem** [conjure-up/conjure-up#1546] opened 2018-11-30 21:48 UTC
I'm trying to install K8S on an ubuntu 18.04 eC2 instance and it's failing.

Conjure up installation keeps failing with the same error flannel hook failed: "install" Please see attachment. 
<img width="908" alt="screen shot 2018-11-30 at 4 49 15 pm" src="https://user-images.githubusercontent.com/22197302/49316747-f0c25a80-f4bf-11e8-9358-f6a0392792a3.png">

Here are additional details requested:

which juju
/snap/bin/juju

juju version
2.4.3-bionic-amd64

which conjure-up
/snap/bin/conjure-up

conjure-up --version
conjure-up 2.6.1

 which lxc
/usr/bin/lxc

cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.1 LTS"

Command ran

sudo snap install conjure-up --classic
conjure-up kubernetes

**Comment by seffyroff** [comment] 2018-11-30 22:15
I'm seeing the same symptoms conjuring cdk to local lxd cluster.  In my case I don't have dir-backed storage defined which I know is a requirement, so that could be the issue?

**Comment by battlemidget** [comment] 2018-11-30 23:50
https://docs.conjure-up.io/stable/en/user-manual#users-of-lxd

It mentions how to configure storage

**Comment by JerryBeassem** [comment] 2018-12-01 01:11
It's still failing after configuring a zfs storage. I don't know if the type of storage matter.

**Comment by JerryBeassem** [comment] 2018-12-01 01:11
/snap/bin/lxc storage list
+---------+-------------+--------+--------------------------------------------+---------+
|  NAME   | DESCRIPTION | DRIVER |                   SOURCE                   | USED BY |
+---------+-------------+--------+--------------------------------------------+---------+
| default |             | zfs    | /var/snap/lxd/common/lxd/disks/default.img | 1       |
+---------+-------------+--------+--------------------------------------------+---------+

**Comment by battlemidget** [comment] 2018-12-01 02:08
You need the dir type for storage. zfs/btrfs is not currently supported

**Comment by seffyroff** [comment] 2018-12-01 04:16
I re-ran this spell after adding dir storage to the cluster and got the same result.

**Comment by seffyroff** [comment] 2018-12-01 17:44
The [file's ](https://drive.google.com/file/d/1IuX5pQJlkWub67NkxCVkiU_YiNjngBAE/view?usp=sharing
)52MB, I've added to my GDrive, apologies for the inconvenience.

FYI this was a slightly different deploy, I used Calico.  However the result is the same.

I'll tear this one down now and re-conjure the flannel deploy for capturing debug.

**Comment by seffyroff** [comment] 2018-12-01 19:18
[results-2018-12-01-19-16-48.tar.gz](https://github.com/conjure-up/conjure-up/files/2636260/results-2018-12-01-19-16-48.tar.gz)
Here's the Flannel results.  Let me know if you have any questions or want me to run/capture anything else.  Happy to jump on a screen share if that's helpful.

**Comment by akboyd88** [comment] 2018-12-02 18:16
Running into a similar result when deploying CDK via conjure-up with graylog, helm, and jfrog.
![screen shot 2018-12-02 at 12 05 12](https://user-images.githubusercontent.com/8363252/49343225-030cd780-f62b-11e8-8eed-5fb8ad110c57.png)
[results-2018-12-02-18-02-39.tar.gz](https://github.com/conjure-up/conjure-up/files/2637217/results-2018-12-02-18-02-39.tar.gz)

Deploying onto lxd with default storage pool configured to use the dir driver.

Additional info:
$ which juju
/snap/bin/juju

$ juju version
2.4.3-bionic-amd64

$ which conjure-up
/snap/bin/conjure-up

$ conjure-up --version
conjure-up 2.6.1

$ which lxc
/snap/bin/lxc

$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.1 LTS"

~$ lxc storage list
+------------+-------------+--------+------------------------------------------------+---------+
|    NAME    | DESCRIPTION | DRIVER |                     SOURCE                     | USED BY |
+------------+-------------+--------+------------------------------------------------+---------+
| default    |             | dir    | /var/snap/lxd/common/lxd/storage-pools/default | 16      |
+------------+-------------+--------+------------------------------------------------+---------+
| juju-btrfs |             | btrfs  | /var/snap/lxd/common/lxd/disks/juju-btrfs.img  | 0       |
+------------+-------------+--------+------------------------------------------------+---------+

**Comment by battlemidget** [comment] 2018-12-02 21:00
Thanks we'll take a look asap

**Comment by seffyroff** [comment] 2018-12-03 01:05
FYI I tested the CDK Core Spell with the same environment, it also fails in the same way, and is a bit speedier to deploy for testing iteration :)

**Comment by akboyd88** [comment] 2018-12-03 01:11
For what it's worth I'm seeing this error in debug-logs whenever I resolve the flannel unit through juju

`unit-flannel-0: 00:55:18 INFO juju.worker.uniter awaiting error resolution for "install" hook
unit-flannel-0: 00:55:19 INFO unit.flannel/0.juju-log Reactive main running for hook install
unit-flannel-0: 00:55:19 INFO unit.flannel/0.juju-log Invoking reactive handler: reactive/flannel.py:26:install_flannel_binaries
unit-flannel-0: 00:55:20 INFO unit.flannel/0.juju-log ['tar', 'xfz', '/var/lib/juju/agents/unit-flannel-0/resources/flannel-amd64/flannel.tar.gz', '-C', '/var/lib/juju/agents/unit-flannel-0/charm/files/flannel']
unit-flannel-0: 00:55:20 DEBUG unit.flannel/0.install removed '/usr/local/bin/flanneld'
unit-flannel-0: 00:55:20 DEBUG unit.flannel/0.install '/var/lib/juju/agents/unit-flannel-0/charm/files/flannel/flanneld' -> '/usr/local/bin/flanneld'
unit-flannel-0: 00:55:20 DEBUG unit.flannel/0.install removed '/usr/local/bin/etcdctl'
unit-flannel-0: 00:55:20 DEBUG unit.flannel/0.install '/var/lib/juju/agents/unit-flannel-0/charm/files/flannel/etcdctl' -> '/usr/local/bin/etcdctl'
unit-flannel-0: 00:55:20 DEBUG unit.flannel/0.install install: cannot stat '/var/lib/juju/agents/unit-flannel-0/charm/files/flannel/flannel': No such file or directory
unit-flannel-0: 00:55:20 ERROR unit.flannel/0.juju-log Hook error:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-flannel-0/.venv/lib/python3.6/site-packages/charms/reactive/__init__.py", line 73, in main
    bus.dispatch(restricted=restricted_mode)
  File "/var/lib/juju/agents/unit-flannel-0/.venv/lib/python3.6/site-packages/charms/reactive/bus.py", line 390, in dispatch
    _invoke(other_handlers)
  File "/var/lib/juju/agents/unit-flannel-0/.venv/lib/python3.6/site-packages/charms/reactive/bus.py", line 359, in _invoke
    handler.invoke()
  File "/var/lib/juju/agents/unit-flannel-0/.venv/lib/python3.6/site-packages/charms/reactive/bus.py", line 181, in invoke
    self._action(*args)
  File "/var/lib/juju/agents/unit-flannel-0/charm/reactive/flannel.py", line 67, in install_flannel_binaries
    check_call(install)
  File "/usr/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['install', '-v', '-D', '/var/lib/juju/agents/unit-flannel-0/charm/files/flannel/flannel', '/opt/cni/bin/flannel']' returned non-zero exit status 1.
`

**Comment by battlemidget** [comment] 2018-12-03 15:37
Think we tracked it down to percona-cluster, will update soon as we has a resolution

**Comment by seffyroff** [comment] 2018-12-03 17:15
Thanks for looking into it!  Looking forward to grabbing the update when it becomes available.

**Comment by seffyroff** [comment] 2018-12-04 01:07
I updated my snap to   edge:      2.6.1-20181204.0012 (1033) 109MB classic
And deployed CDK, it fails on Flannel in the same way.
[results-2018-12-04-01-06-13.tar.gz](https://github.com/conjure-up/conjure-up/files/2641926/results-2018-12-04-01-06-13.tar.gz)

**Comment by seffyroff** [comment] 2018-12-04 01:16
OK I manually ran juju upgrade-charm flannel, which set the rev to 340 (which I thought it was already at) and it appears to be working now, or at least it's progressed further - Flannel is reporting a subnet.  I'll update in a bit..

**Comment by JerryBeassem** [comment] 2018-12-04 21:07
conjure-up kubernetes continuously failed with this error
<img width="923" alt="screen shot 2018-12-04 at 10 04 25 am" src="https://user-images.githubusercontent.com/22197302/49472820-6ab75400-f7de-11e8-9a24-4adb5f3c4f8e.png">

after I quit the install and run juju status obviously same errors on flannel.
any ideas?

**Comment by Cynerva** [comment] 2018-12-05 15:08
Please follow the workaround here for now: https://github.com/conjure-up/conjure-up/issues/1545#issuecomment-444291565

I'm closing this issue as it is a duplicate of https://github.com/conjure-up/conjure-up/issues/1545. Please continue discussion there.

**Closed by Cynerva** 2018-12-05 15:08 UTC

**Comment by JerryBeassem** [comment] 2018-12-05 15:10
I'll try the workaround thank you
