### ISSUE TITLE
No networks after running Openstack with NovaLXD deployment

### ISSUE THREAD

**Issue by mgaruccio** [conjure-up/conjure-up#1432] opened 2018-05-15 22:48 UTC
## Report

Thank you for trying **conjure-up**! Before reporting a bug please make sure you've gone through this checklist:

- [no] Is this problem already documented at https://docs.ubuntu.com/conjure-up/en/troubleshoot#common-spell-problems
- [no] Is conjure-up running inside a virtual machine?
- [yes] Is this problem reproducible with `sudo snap refresh conjure-up --edge`?

## Please provide the output of the following commands

```
which juju - /snap/bin/juju
juju version - 2.3.7-xenial-amd64

which conjure-up - /snap/bin/conjure-up
conjure-up --version - conjure-up 2.5.6

which lxc - /snap/bin/lxc
/snap/bin/lxc config show - 
config:
  core.https_address: '[::]'

/snap/bin/lxc version - 
Client version: 3.0.0
Server version: 3.0.0

cat /etc/lsb-release - 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.4 LTS"

Please attach tarball of **~/.cache/conjure-up**:

```
tar cvzf conjure-up.tar.gz ~/.cache/conjure-up
[conjure-up.tar.gz](https://github.com/conjure-up/conjure-up/files/2006988/conjure-up.tar.gz)

```

## Sosreport

Please attach a sosreport:


```
sudo apt install sosreport
sosreport

The resulting output file can be attached to this issue.
[sosreport-mgaruccio-20180515184306.tar.gz](https://github.com/conjure-up/conjure-up/files/2007005/sosreport-mgaruccio-20180515184306.tar.gz)

### MAAS Users
Which version of MAAS?

## Commands ran

Please outline what commands were run to install and execute conjure-up:

conjure-up
then selected the novaLXD spell and default options

## Additional Information
After running a new deployment on a fresh Ubuntu server 16.04 instance on a physical machine everything shows as deployed in conjure-up but there are no networks present in the openstack environment.

**Comment by walkerandco** [comment] 2018-05-16 08:35
I've found a similar situation with kubernetes. There appears to be a bug where conjure-up ignores lxdbr0 and overrides the bridge at eth0 in the configuration profile default in lxd. I can confirm that this is the case with latest install of LTS release of lxd and latest repo version of conjure-up.

Manual fix: lxd profile edit default, edit default bridge to use lxdbr0 and not the substitute provided by conjure-up.

The root of the problem appears to be that conjure-up does not list lxdbr0 and so to proceed with setup overrides the default bridge in lxd.

**Comment by walkerandco** [comment] 2018-05-17 07:43
What's your output of lxc --version?

**Comment by mgaruccio** [comment] 2018-05-17 11:02
Lxc version output 

Client version: 3.0.0
Server version: 3.0.0

**Comment by walkerandco** [comment] 2018-05-18 09:59
That's the latest version, what's the output of ifconfig?

**Comment by walkerandco** [comment] 2018-05-19 10:52
That's very strange. You have two bridges. If you launch a standard lxd container, it should use lxdbr0. Conjure-up has created its own bridge. So, if your juju machines are using lxdbr0 and not conjure-up0, then  that might explain the issue. What is the output of this command?

lxc info [containernamehere] 

Pick any container with a name starting with juju.

**Comment by roelvanniekerk** [comment] 2018-05-20 10:41
I'm having the exact same issues, with a brand new install of Ubuntu (16.04, 17.10 and 18.04) and a deployment of openstack-novalxd (latest stable release).

Next to the networks, also the images are not provided correctly. I did several deployments and sometimes they don't appear at all in the image overview, sometimes they do appear to be there, but then it seems to be only the 'metadata' and creating an actual instance based on the selected image doesn't work (with the very describing error _maximum amount of retries exceeded_).

The bridge configuration is unlikely to be the problem. My configuration is as follows and was always working fine:
I have a physical network interface, directly connected to my router with a bridge on top of it named _lxdbr0_. This bridge is attached to the default profile of lxd with the following command:
`/snap/bin/lxc network attach-profile lxdbr0 default enp8s0`
where enp8s0 is the physical network interface.
At deploying openstack, conjure-up asks for a bridge, which defaults to lxdbr0. This way, all juju containers deployed by conjure-up get an IP address from the DHCP server of my router, making them directly available on my internal network. What I used to do then in Openstack (Horizon), was reconfigure the provided external network to be in the same IP range as my router/dhcp, so that I could assign floating IPs to my Openstack instances that are reachable from my internal network.
All working perfectly fine! Until now...

I did some fiddling around on a fresh install of Ubuntu 18.04 (but the version doesn't really matter as said earlier), of which I'll sumarize my findings below.

My bridge configuration is as described above, now installing openstack with conjure-up, leaving all settings to default:
`osadmin@openstack:~$ conjure-up openstack-novalxd`
Resulting in a nicely deployed openstack environment, with all healthy juju containers and no errors at all, as it seems at first...

As no networks or images are available, I went on a search for the scripting that should create these. Apparently those scripts are executed from the nova cloud controller.
`osadmin@openstack:~$ juju ssh nova-cloud-controller/0`

**Comment by roelvanniekerk** [comment] 2018-05-20 11:10
I'm having the exact same issues, with a brand new install of Ubuntu (16.04, 17.10 and 18.04) and a deployment of openstack-novalxd (latest stable release).

Next to the networks, also the images are not provided correctly. I did several deployments and sometimes they don't appear at all in the image overview, sometimes they do appear to be there, but 'stuff' goes wrong at creating an actual instance based on a provided image, with the very describing error _maximum amount of retries exceeded_.

The bridge configuration is unlikely to be the problem. My configuration is as follows and was always working fine:
I have a physical network interface, directly connected to my router with a bridge on top of it named `lxdbr0`. This bridge is attached to the default profile of lxd with the following command:
`/snap/bin/lxc network attach-profile lxdbr0 default enp8s0` where `enp8s0` is the physical network interface.

At deploying openstack, conjure-up asks for a bridge, which defaults to `lxdbr0`. This way, all juju machines deployed by conjure-up get an IP address from the DHCP server of my router, making them directly available on my internal network. What I used to do then in Openstack (Horizon), was reconfigure the provided external network to be in the same IP range as my router/dhcp server, so that I could assign floating IPs to my Openstack instances that are reachable from my physical internal network.
All working perfectly fine! Until now...

I did some fiddling around on a fresh install of Ubuntu 18.04 (but the version doesn't really matter as said earlier), of which I'll sumarize my findings below.

My bridge configuration is as described above, now installing openstack with conjure-up, leaving all settings to default: `osadmin@openstack:~$ conjure-up openstack-novalxd`
Resulting in a nicely deployed openstack environment, with all healthy juju machines and no errors at all, as it seems at first...

As no networks are available, I went on a search for the scripting that should create those. Apparently these scripts are executed from the nova cloud controller.
```
osadmin@openstack:~$ juju ssh nova-cloud-controller/0
ubuntu@juju-335c92-13:~$ cat neutron.log
Traceback (most recent call last):
  File "./neutron-ext-net", line 90, in <module>
    for tenant in [t._info for t in keystone.tenants.list()]:
  File "/usr/lib/python2.7/dist-packages/keystoneclient/v2_0/tenants.py", line 124, in list
    tenant_list = self._list('/tenants%s' % query, 'tenants')
  File "/usr/lib/python2.7/dist-packages/keystoneclient/base.py", line 125, in _list
    resp, body = self.client.get(url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/keystoneauth1/adapter.py", line 304, in get
    return self.request(url, 'GET', **kwargs)
  File "/usr/lib/python2.7/dist-packages/keystoneauth1/adapter.py", line 463, in request
    resp = super(LegacyJsonAdapter, self).request(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/keystoneauth1/adapter.py", line 189, in request
    return self.session.request(url, method, **kwargs)
  File "/usr/lib/python2.7/dist-packages/keystoneauth1/session.py", line 573, in request
    auth_headers = self.get_auth_headers(auth)
  File "/usr/lib/python2.7/dist-packages/keystoneauth1/session.py", line 900, in get_auth_headers
    return auth.get_headers(self, **kwargs)
  File "/usr/lib/python2.7/dist-packages/keystoneauth1/plugin.py", line 95, in get_headers
    token = self.get_token(session)
  File "/usr/lib/python2.7/dist-packages/keystoneauth1/identity/base.py", line 88, in get_token
    return self.get_access(session).auth_token
  File "/usr/lib/python2.7/dist-packages/keystoneauth1/identity/base.py", line 134, in get_access
    self.auth_ref = self.get_auth_ref(session)
  File "/usr/lib/python2.7/dist-packages/keystoneauth1/identity/v2.py", line 63, in get_auth_ref
    authenticated=False, log=False)
  File "/usr/lib/python2.7/dist-packages/keystoneauth1/session.py", line 848, in post
    return self.request(url, 'POST', **kwargs)
  File "/usr/lib/python2.7/dist-packages/keystoneauth1/session.py", line 737, in request
    raise exceptions.from_response(resp, method, url)
keystoneauth1.exceptions.http.NotFound: (http://192.168.1.69:5000/v3/tokens): The resource could not be found. (HTTP 404) (Request-ID: req-85377c62-7414-4742-bbf5-c141b65ddadd)
Traceback (most recent call last):
  File "./neutron-tenant-net", line 70, in <module>
    region_name=os.environ['OS_REGION_NAME'])
  File "/usr/lib/python2.7/dist-packages/keystoneclient/v2_0/client.py", line 176, in __init__
    self.authenticate()
  File "/usr/lib/python2.7/dist-packages/keystoneclient/httpclient.py", line 578, in authenticate
    resp = self.get_raw_token_from_identity_service(**kwargs)
  File "/usr/lib/python2.7/dist-packages/keystoneclient/v2_0/client.py", line 220, in get_raw_token_from_identity_service
    _("Authorization Failed: %s") % e)
keystoneauth1.exceptions.auth.AuthorizationFailure: Authorization Failed: (http://192.168.1.69:5000/v3/tokens): The resource could not be found. (HTTP 404) (Request-ID: req-eabbf33e-4f75-4ac1-a00e-46434c201320)
neutron CLI is deprecated and will be removed in the future. Use openstack CLI instead.
Unable to find security_group with name or id '"3e281e30-c91f-4c93-a695-b9c2e1783161"'
neutron CLI is deprecated and will be removed in the future. Use openstack CLI instead.
Unable to find security_group with name or id '"3e281e30-c91f-4c93-a695-b9c2e1783161"'
neutron CLI is deprecated and will be removed in the future. Use openstack CLI instead.
Unable to find security_group with name or id 'null'
neutron CLI is deprecated and will be removed in the future. Use openstack CLI instead.
Unable to find security_group with name or id 'null'
neutron CLI is deprecated and will be removed in the future. Use openstack CLI instead.
Unable to find security_group with name or id 'null'
neutron CLI is deprecated and will be removed in the future. Use openstack CLI instead.
Unable to find security_group with name or id 'null'
neutron CLI is deprecated and will be removed in the future. Use openstack CLI instead.
Unable to find security_group with name or id 'null'
neutron CLI is deprecated and will be removed in the future. Use openstack CLI instead.
Unable to find security_group with name or id 'null'
neutron CLI is deprecated and will be removed in the future. Use openstack CLI instead.
Unable to find security_group with name or id 'null'
neutron CLI is deprecated and will be removed in the future. Use openstack CLI instead.
Unable to find security_group with name or id 'null'
```
The key seems to be in the `(http://192.168.1.69:5000/v3/tokens): The resource could not be found. (HTTP 404)` message. This should be `/v3/auth/tokens`. So the next thing to do was somehow fix this.
To just try out some things I made changes in `/usr/lib/python2.7/dist-packages/keystoneauth1/identity/v2.py` and `/usr/lib/python2.7/dist-packages/keystoneclient/v2_0/client.py` (this isn't the right place to fix this I guess) which seemingly solved both 404 messages, but led to the following:
```
ubuntu@juju-335c92-13:~$ chmod +x neutron.sh
ubuntu@juju-335c92-13:~$ ./neutron.sh
Neutron networking is now configured and is available to you during instance creation.ubuntu@juju-335c92-13:~$ cat neutron.log
Traceback (most recent call last):
  File "./neutron-ext-net", line 90, in <module>
    for tenant in [t._info for t in keystone.tenants.list()]:
  File "/usr/lib/python2.7/dist-packages/keystoneclient/v2_0/tenants.py", line 124, in list
    tenant_list = self._list('/tenants%s' % query, 'tenants')
  File "/usr/lib/python2.7/dist-packages/keystoneclient/base.py", line 125, in _list
    resp, body = self.client.get(url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/keystoneauth1/adapter.py", line 304, in get
    return self.request(url, 'GET', **kwargs)
  File "/usr/lib/python2.7/dist-packages/keystoneauth1/adapter.py", line 463, in request
    resp = super(LegacyJsonAdapter, self).request(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/keystoneauth1/adapter.py", line 189, in request
    return self.session.request(url, method, **kwargs)
  File "/usr/lib/python2.7/dist-packages/keystoneauth1/session.py", line 573, in request
    auth_headers = self.get_auth_headers(auth)
  File "/usr/lib/python2.7/dist-packages/keystoneauth1/session.py", line 900, in get_auth_headers
    return auth.get_headers(self, **kwargs)
  File "/usr/lib/python2.7/dist-packages/keystoneauth1/plugin.py", line 95, in get_headers
    token = self.get_token(session)
  File "/usr/lib/python2.7/dist-packages/keystoneauth1/identity/base.py", line 88, in get_token
    return self.get_access(session).auth_token
  File "/usr/lib/python2.7/dist-packages/keystoneauth1/identity/base.py", line 134, in get_access
    self.auth_ref = self.get_auth_ref(session)
  File "/usr/lib/python2.7/dist-packages/keystoneauth1/identity/v2.py", line 64, in get_auth_ref
    authenticated=False, log=False)
  File "/usr/lib/python2.7/dist-packages/keystoneauth1/session.py", line 848, in post
    return self.request(url, 'POST', **kwargs)
  File "/usr/lib/python2.7/dist-packages/keystoneauth1/session.py", line 737, in request
    raise exceptions.from_response(resp, method, url)
keystoneauth1.exceptions.http.BadRequest: 'identity' is a required property

Failed validating 'required' in schema:
    {'properties': {'identity': {'properties': {'methods': {'items': {'type': 'string'},
                                                            'type': 'array'},
                                                'password': {'properties': {'user': {'properties': {'domain': {'properties': {'id': {'type': 'string'},
                                                                                                                              'name': {'type': 'string'}},
                                                                                                               'type': 'object'},
                                                                                                    'id': {'type': 'string'},
                                                                                                    'name': {'type': 'string'},
                                                                                                    'password': {'type': 'string'}},
                                                                                     'type': 'object'}},
                                                             'type': 'object'},
                                                'token': {'properties': {'id': {'type': 'string'}},
                                                          'required': ['id'],
                                                          'type': 'object'}},
                                 'required': ['methods'],
                                 'type': 'object'},
                    'scope': {'properties': {'OS-TRUST:trust': {'properties': {'id': {'type': 'string'}},
                                                                'type': 'object'},
                                             'domain': {'properties': {'id': {'type': 'string'},
                                                                       'name': {'type': 'string'}},
                                                        'type': 'object'},
                                             'project': {'properties': {'domain': {'properties': {'id': {'type': 'string'},
                                                                                                  'name': {'type': 'string'}},
                                                                                   'type': 'object'},
                                                                        'id': {'type': 'string'},
                                                                        'name': {'type': 'string'}},
                                                         'type': 'object'},
                                             'system': {'properties': {'all': {'enum': [True,
                                                                                        False],
                                                                               'type': 'boolean'}},
                                                        'type': 'object'}},
                              'type': ['object', 'string']}},
     'required': ['identity'],
     'type': 'object'}

On instance:
    {u'passwordCredentials': {u'password': u'openstack',
                              u'username': u'admin'},
     u'tenantName': u'admin'} (HTTP 400) (Request-ID: req-818d9ca5-6ba0-4b43-8124-961b43788390)
Traceback (most recent call last):
  File "./neutron-tenant-net", line 70, in <module>
    region_name=os.environ['OS_REGION_NAME'])
  File "/usr/lib/python2.7/dist-packages/keystoneclient/v2_0/client.py", line 176, in __init__
    self.authenticate()
  File "/usr/lib/python2.7/dist-packages/keystoneclient/httpclient.py", line 578, in authenticate
    resp = self.get_raw_token_from_identity_service(**kwargs)
  File "/usr/lib/python2.7/dist-packages/keystoneclient/v2_0/client.py", line 221, in get_raw_token_from_identity_service
    _("Authorization Failed: %s") % e)
keystoneauth1.exceptions.auth.AuthorizationFailure: Authorization Failed: 'identity' is a required property

Failed validating 'required' in schema:
    {'properties': {'identity': {'properties': {'methods': {'items': {'type': 'string'},
                                                            'type': 'array'},
                                                'password': {'properties': {'user': {'properties': {'domain': {'properties': {'id': {'type': 'string'},
                                                                                                                              'name': {'type': 'string'}},
                                                                                                               'type': 'object'},
                                                                                                    'id': {'type': 'string'},
                                                                                                    'name': {'type': 'string'},
                                                                                                    'password': {'type': 'string'}},
                                                                                     'type': 'object'}},
                                                             'type': 'object'},
                                                'token': {'properties': {'id': {'type': 'string'}},
                                                          'required': ['id'],
                                                          'type': 'object'}},
                                 'required': ['methods'],
                                 'type': 'object'},
                    'scope': {'properties': {'OS-TRUST:trust': {'properties': {'id': {'type': 'string'}},
                                                                'type': 'object'},
                                             'domain': {'properties': {'id': {'type': 'string'},
                                                                       'name': {'type': 'string'}},
                                                        'type': 'object'},
                                             'project': {'properties': {'domain': {'properties': {'id': {'type': 'string'},
                                                                                                  'name': {'type': 'string'}},
                                                                                   'type': 'object'},
                                                                        'id': {'type': 'string'},
                                                                        'name': {'type': 'string'}},
                                                         'type': 'object'},
                                             'system': {'properties': {'all': {'enum': [True,
                                                                                        False],
                                                                               'type': 'boolean'}},
                                                        'type': 'object'}},
                              'type': ['object', 'string']}},
     'required': ['identity'],
     'type': 'object'}

On instance:
    {u'passwordCredentials': {u'password': u'openstack',
                              u'username': u'admin'},
     u'tenantName': u'admin'} (HTTP 400) (Request-ID: req-31afdfb2-34ac-42d6-a9a8-2fbb2b85a009)
neutron CLI is deprecated and will be removed in the future. Use openstack CLI instead.
Unable to find security_group with name or id '"3e281e30-c91f-4c93-a695-b9c2e1783161"'
neutron CLI is deprecated and will be removed in the future. Use openstack CLI instead.
Unable to find security_group with name or id '"3e281e30-c91f-4c93-a695-b9c2e1783161"'
neutron CLI is deprecated and will be removed in the future. Use openstack CLI instead.
Unable to find security_group with name or id 'null'
neutron CLI is deprecated and will be removed in the future. Use openstack CLI instead.
Unable to find security_group with name or id 'null'
neutron CLI is deprecated and will be removed in the future. Use openstack CLI instead.
Unable to find security_group with name or id 'null'
neutron CLI is deprecated and will be removed in the future. Use openstack CLI instead.
Unable to find security_group with name or id 'null'
neutron CLI is deprecated and will be removed in the future. Use openstack CLI instead.
Unable to find security_group with name or id 'null'
neutron CLI is deprecated and will be removed in the future. Use openstack CLI instead.
Unable to find security_group with name or id 'null'
neutron CLI is deprecated and will be removed in the future. Use openstack CLI instead.
Unable to find security_group with name or id 'null'
neutron CLI is deprecated and will be removed in the future. Use openstack CLI instead.
Unable to find security_group with name or id 'null'
ubuntu@juju-335c92-13:~$
```
and that's where I'm stuck...

I'm hoping now that @mgaruccio could confirm that this is also happening on his system, so that I'm not all alone with above errors :-)

**Comment by mgaruccio** [comment] 2018-05-20 17:05
@walkerandco - here is the output of lxc info:

Name: juju-e256d8-0
Remote: unix://
Architecture: x86_64
Created: 2018/05/14 03:06 UTC
Status: Running
Type: persistent
Profiles: default, juju-controller
Pid: 3510
Ips:
  lo:	inet	127.0.0.1
  lo:	inet6	::1
  lxdbr0:	inet6	fe80::54a9:41ff:fedb:54b2
  lxdbr0:	inet6	fe80::1
  eth0:	inet	10.217.145.162	vethUVMQTG
  eth0:	inet6	fe80::216:3eff:feba:eed0	vethUVMQTG
Resources:
  Processes: 400
  CPU usage:
    CPU usage (in seconds): 14026
  Memory usage:
    Memory (current): 1.43GB
    Memory (peak): 2.10GB
  Network usage:
    gretap0:
      Bytes received: 0B
      Bytes sent: 0B
      Packets received: 0
      Packets sent: 0
    lo:
      Bytes received: 19.33GB
      Bytes sent: 19.33GB
      Packets received: 46547864
      Packets sent: 46547864
    lxdbr0:
      Bytes received: 0B
      Bytes sent: 470B
      Packets received: 0
      Packets sent: 5
    eth0:
      Bytes received: 3.42GB
      Bytes sent: 1.22GB
      Packets received: 4572690
      Packets sent: 4072461
    gre0:
      Bytes received: 0B
      Bytes sent: 0B
      Packets received: 0
      Packets sent: 0


@roelvanniekerk I was seeing issues with images as well but those seemed to be resolved by moving to the edge release.  Looking at the results you posted I noticed that a credential object is being created with a username and password, with this being the first release that also requires a domain when logging in to the GUI I'm wondering if that also needs to be included in the credential object?

**Comment by walkerandco** [comment] 2018-05-21 04:53
@mgaruccio Looking at your lxc info, it appears that your lxd bridge isn't assigning ip addresses. Try creating a new bridge with network create and assign this to the default profile. Check your lxc info again and if nothing is there it could be a broken lxc install in which case it might be worth raising a separate bug report for lxd too.

**Closed** 2018-09-25 19:48 UTC
Labels: wontfix
